## Sorting and Grouping
The Search service offers the ability to organize your result set in different ways.  Whether you choose to sort based on a specific property, group properties or boost the result set, you have the option to override the default ordering returned. In addition, you can also use navigation to organize your buckets of data returned.

By default, the result set will provide some basic ranking, depending on the type of query or filter performed.

In [1]:
import lseg.data as ld
from lseg.data.content import search
import pandas as pd

# Default session - desktop
ld.open_session()

In [2]:
pd.set_option('display.max_colwidth', 140)
ld.__version__

'2.1.1'

#### Example - Default ranking and how to boost results
To demonstrate default sorting, I'm going to search for documents that match a specific ticker. This will result in the documents ranked based on the relevancy and scores assigned to each document.

Search for Vodafone (VOD) against the ticker:

In [3]:
ld.discovery.search(
    filter = "TickerSymbol eq 'VOD'",
    select = "_, RCSExchangeCountryLeaf"
)

,BusinessEntity,DocumentTitle,PermID,PI,RIC,RCSExchangeCountryLeaf
0,QUOTExEQUITY,"Vodafone Group PLC, Ordinary Share, London Stock Exchange",55836053361,1049261,VOD.L,United Kingdom
1,QUOTExEQUITY,"Vodacom Group Ltd, Ordinary Share, Johannesburg Stock Exchange",55849756323,59938825,VODJ.J,South Africa
2,QUOTExEQUITY,"Johannesburg Stock Exchange Vodacom Group SSF Equity Future Continuation 1, Equity Future, ZAR, Johannesburg Stock Exchange",21481084690,60188651,VODQc1,South Africa
3,QUOTExEQUITY,"Johannesburg Stock Exchange Vodacom Group Limited Cash Settled SSF Equity Future Continuation 1, Equity Future, ZAR, Johannesburg Stock ...",21508525903,113268320,VODSc1,South Africa
4,QUOTExEQUITY,"Johannesburg Stock Exchange Vodacom Group Ltd SSF Cash Settled Dividend Neutral Equity Future Continuation 1, Equity Future, ZAR, Johann...",21707726176,381845837,VODTc1,South Africa
5,QUOTExEQUITY,"Johannesburg Stock Exchange Vodafone Group PLC Dividend Neutral Equity Future Continuation 1, Equity Future, ZAR, Johannesburg Stock Exc...",21481060885,53826719,VODDc1,South Africa
6,QUOTExEQUITY,"Johannesburg Stock Exchange Vodacom Group Limited SSF Dividend Neutral Equity Future Continuation 1, Equity Future, ZAR, Johannesburg St...",21481183689,79060995,VODF1c1,South Africa
7,QUOTExEQUITY,"Johannesburg Stock Exchange Can Do VODX Vodacom Equity Future Continuation 1, Equity Future, ZAR, Johannesburg Stock Exchange",21534036541,148452798,VODXFLc1,South Africa
8,QUOTExEQUITY,"Johannesburg Stock Exchange Vodafone Group PLC IDX Equity Future Continuation 1, Equity Future, ZAR, Johannesburg Stock Exchange",21481060918,53826752,VODGc1,South Africa
9,QUOTExEQUITY,"Johannesburg Stock Exchange Vodacom Group Limited Cash Settled CFD Sabor Equity Future Continuation 1, Equity Future, ZAR, Johannesburg ...",21693141305,363600087,VODSCFDc1,South Africa

The above output ranked the common share 'VOD.L', listed within the UK, at the top.  This is largely due to the fact that 'VOD.L' is the most significant or liquid asset in the list. However, if I decide to override this default ranking by specifying that I want to show the listed documents within the Unitied States at the top, I can do this 
by applying a *Boost* parameter.

In [4]:
ld.discovery.search(
    filter = "TickerSymbol eq 'VOD'",
    boost = "RCSExchangeCountryLeaf eq 'United States'",
    select = "_, RCSExchangeCountryLeaf"
)

,BusinessEntity,DocumentTitle,PermID,PI,RIC,RCSExchangeCountryLeaf
0,QUOTExEQUITY,"Vodafone Group PLC, Depository Receipt, NASDAQ Global Select Consolidated",55839401038,726233,VOD.O,United States
1,QUOTExEQUITY,"Vodafone Group PLC, Depository Receipt, NASDAQ Stock Exchange Global Select Market",55835364259,1092283,VOD.OQ,United States
2,QUOTExEQUITY,"Vodafone Group PLC, Depository Receipt, Cboe BZX Exchange - Nasdaq Global Select Market",55845638958,53705532,VOD.Z,United States
3,QUOTExEQUITY,"Vodafone Group PLC, Depository Receipt, Cboe EDGX Exchange - Nasdaq Global Select Market",21475045362,73238578,VOD.DG,United States
4,QUOTExEQUITY,"Vodafone Group PLC, Depository Receipt, Boston SE when trading NASDAQ Global Select Market",55846134804,55957391,VOD.B,United States
5,QUOTExEQUITY,"Vodafone Group PLC, Depository Receipt, NYSE Arca when trading NASDAQ Global Select Market",55837254988,754172,VOD.P,United States
6,QUOTExEQUITY,"Vodafone Group PLC, Depository Receipt, Cboe BYX Exchange - Nasdaq Global Select Market",21475122433,76383634,VOD.ZY,United States
7,QUOTExEQUITY,"Vodafone Group PLC, Depository Receipt, NYSE National Exchange when trading Nasdaq Global Select Market",55838271132,735992,VOD.C,United States
8,QUOTExEQUITY,"Vodafone Group PLC, Depository Receipt, Cboe EDGA Exchange - Nasdaq Global Select Market",21475045135,73240457,VOD.DY,United States
9,QUOTExEQUITY,"Vodafone Group PLC, Depository Receipt, NYSE Texas When Trading Nasdaq Global Select Market",55838278886,742019,VOD.MW,United States

#### Example - List the youngest CEO's.
The order_by parameters will sort, ascending (default) or descending, based on the birth year property.

Note: In the following example, not every document that identifies a CEO will have a reported birth year. Because we are sorting based on the year they were born, 
all CEO's where the year of birth is not recorded will be bumped to the bottom of the list.

In [6]:
ld.discovery.search(
    view = search.Views.PEOPLE,
    filter = "OfficerDirector(RoleTitleCode eq 'CEO' and RoleStatus eq 'Active')",
    order_by = "YearOfBirth desc, LastName, FirstName",
    select = "FullName, YearOfBirth, DTCharacteristics, CompanyPrimaryOfficerDirectorRIC, PrimaryOfficerDirector"
)

,FullName,YearOfBirth,DTCharacteristics,PrimaryOfficerDirector
0,Gabriel Voinea,2003,"President, Treasurer, Secretary, Director",Rwb Health Inc
1,Jai Adlakha,2000,Chief Executive Officer,Meerut Budaun Expressway Ltd
2,Alfred Karl Andreas Karlsson,2000,External Chief Executive Officer,Nanoscientifica Scandinavia AB
3,Yao-Yun Chang,2000,"Chief Executive Officer, Director",KodyPay Ltd
4,Gagandeep Singh Reehal,2000,"Chief Executive Officer, Founder, Chief Technology Officer",Minus Zero Robotics Pvt Ltd
5,Pracha Chaisuwan,1998,"Chief Executive Officer, Executive Director",Chase Asia PCL
6,Nikhil Krishnan,1998,Chief Executive Officer,Prize Petroleum Company Ltd
7,Aman Sinha,1998,Chief Executive Officer,Brindco Sales Pvt Ltd
8,Carl Fredrik Mikael Akerman,1997,"Chairman of the Board, Chief Executive Officer",VOLTA GREENTECH AB
9,Martins Balodis,1997,"Chief Executive Officer, Director",FACING IT International AB

Instead of sorting by the year of birth, let's organize the output so the company is grouped.

**Note**: While we can see the company's grouped, we can also observe the many of the entries do not have a year of birth recorded.

In [8]:
ld.discovery.search(
    view = search.Views.PEOPLE,
    filter = "OfficerDirector(RoleTitleCode eq 'CEO' and RoleStatus eq 'Active')",
    group_by = "PrimaryOfficerDirector",
    top = 20,
    select = "FullName, YearOfBirth, DTCharacteristics, PrimaryOfficerDirectorRIC, PrimaryOfficerDirector"
)

,FullName,YearOfBirth,DTCharacteristics,PrimaryOfficerDirectorRIC,PrimaryOfficerDirector
0,Satya Nadella,<NA>,"Chairman of the Board, Chief Executive Officer",MSFT.O,Microsoft Corp
1,John W. Stanton,<NA>,Independent Director,MSFT.O,Microsoft Corp
2,Tim D. Cook,<NA>,"Chief Executive Officer, Director",AAPL.O,Apple Inc
3,Andrew R. Jassy,<NA>,"President, Chief Executive Officer, Director",AMZN.O,Amazon.com Inc
4,Sundar Pichai,1972,"Chief Executive Officer, Director",GOOGL.O,Alphabet Inc
5,R. Martin Chavez,<NA>,Director,GOOGL.O,Alphabet Inc
6,Mark Zuckerberg,<NA>,"Chairman of the Board, Chief Executive Officer, Founder",META.O,Meta Platforms Inc
7,Drew W. Houston,<NA>,Independent Director,META.O,Meta Platforms Inc
8,Warren E. Buffett,1930,"Chairman of the Board, Chief Executive Officer",BRKa,Berkshire Hathaway Inc
9,Yongming Wu,<NA>,"Chief Executive Officer, Director",BABA.K,Alibaba Group Holding Ltd
10,Huateng Ma,<NA>,"Executive Chairman of the Board, Chief Executive Officer",0700.HK,Tencent Holdings Ltd
11,Ryan McInerney,<NA>,"Chief Executive Officer, Director",V,Visa Inc
12,Joaquin Boix Duato,<NA>,"Chairman of the Board, Chief Executive Officer",JNJ,Johnson & Johnson
13,Darius E Adamczyk,1966,Independent Director,JNJ,Johnson & Johnson
14,Mary Catherine Beckerle,<NA>,Independent Director,JNJ,Johnson & Johnson
15,Jamie L. Dimon,<NA>,"Chairman of the Board, Chief Executive Officer",JPM,JPMorgan Chase & Co
16,Daniel E. Pinto,<NA>,"President, Chief Operating Officer",JPM,JPMorgan Chase & Co
17,Laurent Freixe,1962,"Chief Executive Officer, Member of the Executive Board",NESN.S,Nestle Ltd
18,Doug McMillon,<NA>,Director,WMT.O,Walmart Inc
19,John R. Furner,<NA>,"President, Chief Executive Officer, Director",WMT.O,Walmart Inc

#### Example - Sorting using Navigators
By default, when you use a navigator against a property, it will sort all results based on the number of matches for each value within a bucket.  For example, if I were to list the top 10 exchanges within Canada, we can see the count value ranked, indicating the number instruments matched on that exchange.

In [9]:
response = search.Definition(
    view = search.Views.EQUITY_QUOTES,
    filter = "RCSExchangeCountryLeaf eq 'Canada'",
    top = 0,
    navigators = "ExchangeName(buckets:10)"
).get_data()
response.data.raw["Navigators"]["ExchangeName"]["Buckets"]

[{'Label': 'Montreal Options Exchange', 'Count': 155279},
 {'Label': 'LSEG', 'Count': 116793},
 {'Label': 'Montreal Exchange', 'Count': 45695},
 {'Label': 'The Toronto Stock Exchange', 'Count': 11899},
 {'Label': 'Nasdaq CXC', 'Count': 11123},
 {'Label': 'Canadian Securities Exchange/PURE - CSE Listed & Other Canadian Listed Securities',
  'Count': 9083},
 {'Label': 'Canadian Composite Quote/Trade', 'Count': 9066},
 {'Label': 'Tradelogiq Omega ATS', 'Count': 8311},
 {'Label': 'Alpha - Canadian ATS', 'Count': 7868},
 {'Label': 'Nasdaq CX2', 'Count': 7848}]

Using the above example, I can instead choose to sort based on the average daily volume within the exchange.  The following search will result in the top 5 Canadian exchanges, ranked based on the 90 day average volume:

In [10]:
response = search.Definition(
    view = search.Views.EQUITY_QUOTES,
    filter = "RCSExchangeCountryLeaf eq 'Canada'",
    top = 0,
    navigators = "ExchangeName(buckets:5, desc:sum_AvgVol90D)"
).get_data()

In [11]:
# Pretty display of the listing
data = []
for exch in response.data.raw["Navigators"]["ExchangeName"]["Buckets"]:
    data.append([exch["Label"], f'{exch["sum_AvgVol90D"]:,}'])

pd.DataFrame(data, columns=["Exchange", "Average 90-day Volume"])

,Exchange,Average 90-day Volume
0,Canadian Composite Quote/Trade,"2,485,644,111.0"
1,The Toronto Stock Exchange,"1,231,058,245.0"
2,TSX Venture Exchange (former Canadian Ventures Exchange),"516,295,796.0"
3,Canadian Securities Exchange - CSE Listed,"123,077,039.0"
4,Canadian Securities Exchange/PURE - CSE Listed & Other Canadian Listed Securities,"60,861,921.0"

In [12]:
ld.close_session()