## Properties / Metadata
The document properties represent the fields that define the data elements you want to retrieve as well as the elements you choose to filter your results.  In addition, properties are at the heart of other Search parameters such as Navigation, Grouping, and Boosting.  There are hundreds of properties available for each View providing critical details needed to fulfill your searching requirements.

In order for you to be successful at search, you will need to understand how to access the available properties, how to determine what values they contain and what they mean.

**Note**: The concepts outlined within this notebook provide the mechanism to manually extract properties and values.  While the techniques outlined are a great tool to better understand these attributes, the tasks to extract these details can be cumbersome and overwhelming.  As a way to significantly reduce this effort, I've written an article, [Accelerating Search: Unlocking the Power of Property Exploration](https://developers.lseg.com/en/article-catalog/article/accelerating-search-unlocking-the-power-of-property-exploration) that will allow users to discover properties and values much easier when searching.

In [23]:
import lseg.data as ld
from lseg.data.content import search
import pandas as pd

# Default session - desktop
ld.open_session()

In [24]:
pd.set_option('display.max_colwidth', 140)
ld.__version__

'2.1.1'

In [ ]:
# Optionally override maximum dataframe rows
#pd.set_option('display.max_rows', 10000)

In [25]:
help(search.Views)

Help on class Views in module lseg.data.content.search._views:

class Views(enum.StrEnum)
 |  Views(*values)
 |
 |  Possible views values to request data from 'search' endpoint
 |
 |  Method resolution order:
 |      Views
 |      enum.StrEnum
 |      builtins.str
 |      enum.ReprEnum
 |      enum.Enum
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __format__(self, format_spec, /) from builtins.str
 |      Return a formatted version of the string as described by format_spec.
 |
 |  __new__(cls, value) from enum.Enum
 |      Create and return a new object.  See help(type) for accurate signature.
 |
 |  __str__(self, /) from builtins.str
 |      Return str(self).
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  BOND_FUT_OPT_QUOTES = <Views.BOND_FUT_OPT_QUOTES: 'BondFutOptQuotes'>
 |
 |  CATALOG_ITEMS = <Views.CATALOG_ITEMS: 'CatalogItems'>
 |
 |  CDS_INSTRUMENTS = <Views.CDS_INSTRUMENTS: 'CdsInstruments'>
 |
 |  CDS_QUOTES = <Views.CDS_QUOTES: 'CdsQuotes'>
 |
 |  CMO_INSTRUMENTS = <Views.CMO_INSTRUMENTS: 'CmoInstruments'>
 |
 |  CMO_QUOTES = <Views.CMO_QUOTES: 'CmoQuotes'>
 |
 |  COMMODITY_QUOTES = <Views.COMMODITY_QUOTES: 'CommodityQuotes'>
 |
 |  DEALS_MERGERS_AND_ACQUISITIONS = <Views.DEALS_MERGERS_AND_ACQUISITIONS...
 |
 |  DERIVATIVE_INSTRUMENTS = <Views.DERIVATIVE_INSTRUMENTS: 'DerivativeIns...
 |
 |  DERIVATIVE_QUOTES = <Views.DERIVATIVE_QUOTES: 'DerivativeQuotes'>
 |
 |  ENTITIES = <Views.ENTITIES: 'Entities'>
 |
 |  EQUITY_DERIVATIVE_INSTRUMENTS = <Views.EQUITY_DERIVATIVE_INSTRUMENTS: ...
 |
 |  EQUITY_DERIVATIVE_QUOTES = <Views.EQUITY_DERIVATIVE_QUOTES: 'EquityDer...
 |
 |  EQUITY_INSTRUMENTS = <Views.EQUITY_INSTRUMENTS: 'EquityInstruments'>
 |
 |  EQUITY_QUOTES = <Views.EQUITY_QUOTES: 'EquityQuotes'>
 |
 |  FIXED_INCOME_INSTRUMENTS = <Views.FIXED_INCOME_INSTRUMENTS: 'FixedInco...
 |
 |  FIXED_INCOME_QUOTES = <Views.FIXED_INCOME_QUOTES: 'FixedIncomeQuotes'>
 |
 |  FUND_QUOTES = <Views.FUND_QUOTES: 'FundQuotes'>
 |
 |  GOV_CORP_INSTRUMENTS = <Views.GOV_CORP_INSTRUMENTS: 'GovCorpInstrument...
 |
 |  GOV_CORP_QUOTES = <Views.GOV_CORP_QUOTES: 'GovCorpQuotes'>
 |
 |  INDEX_INSTRUMENTS = <Views.INDEX_INSTRUMENTS: 'IndexInstruments'>
 |
 |  INDEX_QUOTES = <Views.INDEX_QUOTES: 'IndexQuotes'>
 |
 |  INDICATOR_QUOTES = <Views.INDICATOR_QUOTES: 'IndicatorQuotes'>
 |
 |  INSTRUMENTS = <Views.INSTRUMENTS: 'Instruments'>
 |
 |  INVESTORS = <Views.INVESTORS: 'Investors'>
 |
 |  IRD_QUOTES = <Views.IRD_QUOTES: 'IRDQuotes'>
 |
 |  LOAN_INSTRUMENTS = <Views.LOAN_INSTRUMENTS: 'LoanInstruments'>
 |
 |  LOAN_QUOTES = <Views.LOAN_QUOTES: 'LoanQuotes'>
 |
 |  MONEY_QUOTES = <Views.MONEY_QUOTES: 'MoneyQuotes'>
 |
 |  MORTGAGE_INSTRUMENTS = <Views.MORTGAGE_INSTRUMENTS: 'MortgageInstrumen...
 |
 |  MORT_QUOTES = <Views.MORT_QUOTES: 'MortQuotes'>
 |
 |  MUNICIPAL_INSTRUMENTS = <Views.MUNICIPAL_INSTRUMENTS: 'MunicipalInstru...
 |
 |  MUNICIPAL_QUOTES = <Views.MUNICIPAL_QUOTES: 'MunicipalQuotes'>
 |
 |  ORGANISATIONS = <Views.ORGANISATIONS: 'Organisations'>
 |
 |  PEOPLE = <Views.PEOPLE: 'People'>
 |
 |  PHYSICAL_ASSETS = <Views.PHYSICAL_ASSETS: 'PhysicalAssets'>
 |
 |  QUOTES = <Views.QUOTES: 'Quotes'>
 |
 |  QUOTES_AND_STIRS = <Views.QUOTES_AND_STIRS: 'QuotesAndSTIRs'>
 |
 |  RCS = <Views.RCS: 'RCS'>
 |
 |  SEARCH_ALL = <Views.SEARCH_ALL: 'SearchAll'>
 |
 |  STIRS = <Views.STIRS: 'STIRs'>
 |
 |  VESSEL_PHYSICAL_ASSETS = <Views.VESSEL_PHYSICAL_ASSETS: 'VesselPhysica...
 |
 |  YIELD_CURVE_CONT_QUOTES = <Views.YIELD_CURVE_CONT_QUOTES: 'YieldCurveC...
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from enum.StrEnum:
 |
 |  __repr__(self) from enum.Enum
 |      Return repr(self).
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from builtins.str:
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __contains__(self, key, /)
 |      Return bool(key in self).
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |
 |  __getitem__(self, key, /)
 |      Return self[key].
 |
 |  __getnewargs__(...)
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __hash__(self, /)
 |      Return hash(self).
 |
 |  __iter__(self, /)
 |      Implement iter(self).
 |
 |  __le__(self, value, /)
 |      Return self<=value.
 |
 |  __len__(self, /)
 |      Return len(self).
 |
 |  __lt__(self, value, /)
 |      Return self<value.
 |
 |  __mod__(self, value, /)
 |      Return self%value.
 |
 |  __mul__(self, value, /)
 |      Return self*value.
 |
 |  __ne__(self, value, /)
 |      Return self!=value.
 |
 |  __rmod__(self, value, /)
 |      Return value%self.
 |
 |  __rmul__(self, value, /)
 |      Return value*self.
 |
 |  __sizeof__(self, /)
 |      Return the size of the string in memory, in bytes.
 |
 |  capitalize(self, /)
 |      Return a capitalized version of the string.
 |
 |      More specifically, make the first character have upper case and the rest lower
 |      case.
 |
 |  casefold(self, /)
 |      Return a version of the string suitable for caseless comparisons.
 |
 |  center(self, width, fillchar=' ', /)
 |      Return a centered string of length width.
 |
 |      Padding is done using the specified fill character (default is a space).
 |
 |  count(...)
 |      S.count(sub[, start[, end]]) -> int
 |
 |      Return the number of non-overlapping occurrences of substring sub in
 |      string S[start:end].  Optional arguments start and end are
 |      interpreted as in slice notation.
 |
 |  encode(self, /, encoding='utf-8', errors='strict')
 |      Encode the string using the codec registered for encoding.
 |
 |      encoding
 |        The encoding in which to encode the string.
 |      errors
 |        The error handling scheme to use for encoding errors.
 |        The default is 'strict' meaning that encoding errors raise a
 |        UnicodeEncodeError.  Other possible values are 'ignore', 'replace' and
 |        'xmlcharrefreplace' as well as any other name registered with
 |        codecs.register_error that can handle UnicodeEncodeErrors.
 |
 |  endswith(...)
 |      S.endswith(suffix[, start[, end]]) -> bool
 |
 |      Return True if S ends with the specified suffix, False otherwise.
 |      With optional start, test S beginning at that position.
 |      With optional end, stop comparing S at that position.
 |      suffix can also be a tuple of strings to try.
 |
 |  expandtabs(self, /, tabsize=8)
 |      Return a copy where all tab characters are expanded using spaces.
 |
 |      If tabsize is not given, a tab size of 8 characters is assumed.
 |
 |  find(...)
 |      S.find(sub[, start[, end]]) -> int
 |
 |      Return the lowest index in S where substring sub is found,
 |      such that sub is contained within S[start:end].  Optional
 |      arguments start and end are interpreted as in slice notation.
 |
 |      Return -1 on failure.
 |
 |  format(...)
 |      S.format(*args, **kwargs) -> str
 |
 |      Return a formatted version of S, using substitutions from args and kwargs.
 |      The substitutions are identified by braces ('{' and '}').
 |
 |  format_map(...)
 |      S.format_map(mapping) -> str
 |
 |      Return a formatted version of S, using substitutions from mapping.
 |      The substitutions are identified by braces ('{' and '}').
 |
 |  index(...)
 |      S.index(sub[, start[, end]]) -> int
 |
 |      Return the lowest index in S where substring sub is found,
 |      such that sub is contained within S[start:end].  Optional
 |      arguments start and end are interpreted as in slice notation.
 |
 |      Raises ValueError when the substring is not found.
 |
 |  isalnum(self, /)
 |      Return True if the string is an alpha-numeric string, False otherwise.
 |
 |      A string is alpha-numeric if all characters in the string are alpha-numeric and
 |      there is at least one character in the string.
 |
 |  isalpha(self, /)
 |      Return True if the string is an alphabetic string, False otherwise.
 |
 |      A string is alphabetic if all characters in the string are alphabetic and there
 |      is at least one character in the string.
 |
 |  isascii(self, /)
 |      Return True if all characters in the string are ASCII, False otherwise.
 |
 |      ASCII characters have code points in the range U+0000-U+007F.
 |      Empty string is ASCII too.
 |
 |  isdecimal(self, /)
 |      Return True if the string is a decimal string, False otherwise.
 |
 |      A string is a decimal string if all characters in the string are decimal and
 |      there is at least one character in the string.
 |
 |  isdigit(self, /)
 |      Return True if the string is a digit string, False otherwise.
 |
 |      A string is a digit string if all characters in the string are digits and there
 |      is at least one character in the string.
 |
 |  isidentifier(self, /)
 |      Return True if the string is a valid Python identifier, False otherwise.
 |
 |      Call keyword.iskeyword(s) to test whether string s is a reserved identifier,
 |      such as "def" or "class".
 |
 |  islower(self, /)
 |      Return True if the string is a lowercase string, False otherwise.
 |
 |      A string is lowercase if all cased characters in the string are lowercase and
 |      there is at least one cased character in the string.
 |
 |  isnumeric(self, /)
 |      Return True if the string is a numeric string, False otherwise.
 |
 |      A string is numeric if all characters in the string are numeric and there is at
 |      least one character in the string.
 |
 |  isprintable(self, /)
 |      Return True if the string is printable, False otherwise.
 |
 |      A string is printable if all of its characters are considered printable in
 |      repr() or if it is empty.
 |
 |  isspace(self, /)
 |      Return True if the string is a whitespace string, False otherwise.
 |
 |      A string is whitespace if all characters in the string are whitespace and there
 |      is at least one character in the string.
 |
 |  istitle(self, /)
 |      Return True if the string is a title-cased string, False otherwise.
 |
 |      In a title-cased string, upper- and title-case characters may only
 |      follow uncased characters and lowercase characters only cased ones.
 |
 |  isupper(self, /)
 |      Return True if the string is an uppercase string, False otherwise.
 |
 |      A string is uppercase if all cased characters in the string are uppercase and
 |      there is at least one cased character in the string.
 |
 |  join(self, iterable, /)
 |      Concatenate any number of strings.
 |
 |      The string whose method is called is inserted in between each given string.
 |      The result is returned as a new string.
 |
 |      Example: '.'.join(['ab', 'pq', 'rs']) -> 'ab.pq.rs'
 |
 |  ljust(self, width, fillchar=' ', /)
 |      Return a left-justified string of length width.
 |
 |      Padding is done using the specified fill character (default is a space).
 |
 |  lower(self, /)
 |      Return a copy of the string converted to lowercase.
 |
 |  lstrip(self, chars=None, /)
 |      Return a copy of the string with leading whitespace removed.
 |
 |      If chars is given and not None, remove characters in chars instead.
 |
 |  partition(self, sep, /)
 |      Partition the string into three parts using the given separator.
 |
 |      This will search for the separator in the string.  If the separator is found,
 |      returns a 3-tuple containing the part before the separator, the separator
 |      itself, and the part after it.
 |
 |      If the separator is not found, returns a 3-tuple containing the original string
 |      and two empty strings.
 |
 |  removeprefix(self, prefix, /)
 |      Return a str with the given prefix string removed if present.
 |
 |      If the string starts with the prefix string, return string[len(prefix):].
 |      Otherwise, return a copy of the original string.
 |
 |  removesuffix(self, suffix, /)
 |      Return a str with the given suffix string removed if present.
 |
 |      If the string ends with the suffix string and that suffix is not empty,
 |      return string[:-len(suffix)]. Otherwise, return a copy of the original
 |      string.
 |
 |  replace(self, old, new, count=-1, /)
 |      Return a copy with all occurrences of substring old replaced by new.
 |
 |        count
 |          Maximum number of occurrences to replace.
 |          -1 (the default value) means replace all occurrences.
 |
 |      If the optional argument count is given, only the first count occurrences are
 |      replaced.
 |
 |  rfind(...)
 |      S.rfind(sub[, start[, end]]) -> int
 |
 |      Return the highest index in S where substring sub is found,
 |      such that sub is contained within S[start:end].  Optional
 |      arguments start and end are interpreted as in slice notation.
 |
 |      Return -1 on failure.
 |
 |  rindex(...)
 |      S.rindex(sub[, start[, end]]) -> int
 |
 |      Return the highest index in S where substring sub is found,
 |      such that sub is contained within S[start:end].  Optional
 |      arguments start and end are interpreted as in slice notation.
 |
 |      Raises ValueError when the substring is not found.
 |
 |  rjust(self, width, fillchar=' ', /)
 |      Return a right-justified string of length width.
 |
 |      Padding is done using the specified fill character (default is a space).
 |
 |  rpartition(self, sep, /)
 |      Partition the string into three parts using the given separator.
 |
 |      This will search for the separator in the string, starting at the end. If
 |      the separator is found, returns a 3-tuple containing the part before the
 |      separator, the separator itself, and the part after it.
 |
 |      If the separator is not found, returns a 3-tuple containing two empty strings
 |      and the original string.
 |
 |  rsplit(self, /, sep=None, maxsplit=-1)
 |      Return a list of the substrings in the string, using sep as the separator string.
 |
 |        sep
 |          The separator used to split the string.
 |
 |          When set to None (the default value), will split on any whitespace
 |          character (including \n \r \t \f and spaces) and will discard
 |          empty strings from the result.
 |        maxsplit
 |          Maximum number of splits.
 |          -1 (the default value) means no limit.
 |
 |      Splitting starts at the end of the string and works to the front.
 |
 |  rstrip(self, chars=None, /)
 |      Return a copy of the string with trailing whitespace removed.
 |
 |      If chars is given and not None, remove characters in chars instead.
 |
 |  split(self, /, sep=None, maxsplit=-1)
 |      Return a list of the substrings in the string, using sep as the separator string.
 |
 |        sep
 |          The separator used to split the string.
 |
 |          When set to None (the default value), will split on any whitespace
 |          character (including \n \r \t \f and spaces) and will discard
 |          empty strings from the result.
 |        maxsplit
 |          Maximum number of splits.
 |          -1 (the default value) means no limit.
 |
 |      Splitting starts at the front of the string and works to the end.
 |
 |      Note, str.split() is mainly useful for data that has been intentionally
 |      delimited.  With natural text that includes punctuation, consider using
 |      the regular expression module.
 |
 |  splitlines(self, /, keepends=False)
 |      Return a list of the lines in the string, breaking at line boundaries.
 |
 |      Line breaks are not included in the resulting list unless keepends is given and
 |      true.
 |
 |  startswith(...)
 |      S.startswith(prefix[, start[, end]]) -> bool
 |
 |      Return True if S starts with the specified prefix, False otherwise.
 |      With optional start, test S beginning at that position.
 |      With optional end, stop comparing S at that position.
 |      prefix can also be a tuple of strings to try.
 |
 |  strip(self, chars=None, /)
 |      Return a copy of the string with leading and trailing whitespace removed.
 |
 |      If chars is given and not None, remove characters in chars instead.
 |
 |  swapcase(self, /)
 |      Convert uppercase characters to lowercase and lowercase characters to uppercase.
 |
 |  title(self, /)
 |      Return a version of the string where each word is titlecased.
 |
 |      More specifically, words start with uppercased characters and all remaining
 |      cased characters have lower case.
 |
 |  translate(self, table, /)
 |      Replace each character in the string using the given translation table.
 |
 |        table
 |          Translation table, which must be a mapping of Unicode ordinals to
 |          Unicode ordinals, strings, or None.
 |
 |      The table must implement lookup/indexing via __getitem__, for instance a
 |      dictionary or list.  If this operation raises LookupError, the character is
 |      left untouched.  Characters mapped to None are deleted.
 |
 |  upper(self, /)
 |      Return a copy of the string converted to uppercase.
 |
 |  zfill(self, width, /)
 |      Pad a numeric string with zeros on the left, to fill a field of the given width.
 |
 |      The string is never truncated.
 |
 |  ----------------------------------------------------------------------
 |  Static methods inherited from builtins.str:
 |
 |  maketrans(...)
 |      Return a translation table usable for str.translate().
 |
 |      If there is only one argument, it must be a dictionary mapping Unicode
 |      ordinals (integers) or characters to Unicode ordinals, strings or None.
 |      Character keys will be then converted to ordinals.
 |      If there are two arguments, they must be strings of equal length, and
 |      in the resulting dictionary, each character in x will be mapped to the
 |      character at the same position in y. If there is a third argument, it
 |      must be a string, whose characters will be mapped to None in the result.
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from enum.Enum:
 |
 |  __dir__(self)
 |      Returns public methods and other interesting attributes.
 |
 |  __init__(self, *args, **kwds)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __reduce_ex__(self, proto)
 |      Helper for pickle.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from enum.Enum:
 |
 |  name
 |      The name of the Enum member.
 |
 |  value
 |      The value of the Enum member.
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties inherited from enum.EnumType:
 |
 |  __members__
 |      Returns a mapping of member name->value.
 |
 |      This mapping lists all enum members, including aliases. Note that this
 |      is a read-only view of the internal mapping.

#### Metadata
MetaData is a convenient service that allows you to list all available properties within a View.  To properly build a metadata list for inspection, you can issue the following:

In [27]:
# Specify the view
response = search.metadata.Definition(
    view = search.Views.COMMODITY_QUOTES
).get_data()
response.data.df

,Type,Searchable,Sortable,Navigable,Groupable,Exact,Symbol
AAACurrencyBondBenchmarkChain,String,False,False,False,False,False,False
AACurrencyBondBenchmarkChain,String,False,False,False,False,False,False
ABSMBSBondsRIC,String,False,False,False,False,False,False
ActivityDate,Date,True,True,True,False,False,False
ACurrencyBondBenchmarkChain,String,False,False,False,False,False,False
...,...,...,...,...,...,...,...
WarrantsCount,Double,True,True,True,False,False,False
WarrantType,String,True,False,False,False,False,False
WarrantTypeName,String,True,False,False,False,False,False
Wert,String,True,False,False,True,False,True
XMSAssetCategory,String,True,False,False,False,False,False

In [ ]:
# Export metadata to a spreadsheet for easy viewing
response.data.df.to_excel("CommodityQuotes.xlsx")

#### Debugging (*_debugall*)
While MetaData will help list all properties available within a View, all properties will not be available for use.  That is, depending on the type of search you perform, will determine which properties will be populated - not all will be.  This is where users can use a technique to list all available properties that are populated, for the specific search requested.

In [28]:
# Query for all documents with the company IBM defined
response=search.Definition(
    query = "IBM",
    top = 1,    # Note: It is critical you select a top=1 because the amount of data returned is very large.
    select = "_debugall"
).get_data()
response.data.raw

{'Total': 42471,
 'Hits': [{'meta': {'_id': '37036',
    '_index': 'sip_organisation_0.0.21',
    '_score': 2839587,
    '_version': 809},
   'raw_source': {'SigDevExist': True,
    'WebsiteName': 'ibm|ibm.com|www.ibm.com',
    'OriginalAccountsCurrency': 'USD',
    'LegalNameJaKana': 'インターナショナルビジネスマシーンズコーポレーション',
    'LoanCount': 0,
    'RCSFilingCountry': 'G:6J',
    'EquityDividends': -6255000000,
    'OAOrgTypeName': 'Business Organization',
    'RCSPartyCountry': 'G:6J',
    'Rofa': 9.733997,
    'CompositeDescriptiveNameZh': '国际商用机器|国际商业机器公司 國際商業機器公司',
    'ICBScheme': '9533',
    'EquitiesCount': 132,
    'TRBC2012PrimaryCode': '1790',
    'OAPermID': '4295904307',
    'PreviousNames': 'COMPUTING-TABULATING-RECORDING-CO.|1911-06-16|1924-02-14',
    'SDCCUSIP': '459200',
    'HasTRFBusSeg': True,
    'GEMPermID': '4295904307',
    'TRBCPrimaryCodeMeaning': 'IT Services & Consulting',
    'LegalNameJaHani': 'インターナショナル･ビジネス･マシーンズ･コーポレーション',
    'OfficersExist': True,
    'CIK': '0000051143',
    'FitchIssuerRating': 'WD',
    'DTSubjectNameJaHira': 'いんたーなしょなるびじねすましーんずこーぽれーしょん',
    'SPsRatingType': 'Issuer/S&P/SPI|Issuer/S&P/SSU|Issuer/S&P/SIS|Issuer/S&P/SIS|Issuer/S&P/SCP|Issuer/S&P/SCP|Issuer/S&P/SSU|Issuer/S&P/SPI|Issuer/S&P/SMU|Issuer/S&P/SMU',
    'PI': '37036',
    'DUNSStripped': '1368083',
    'StaffCosts': -904000000,
    'SDCID': '3104001',
    'IsPublic': True,
    'RCSOrganisationTypeNameML': 'ja 事業法人|zh-Hans 公司|zh-Hant 公司',
    'ShortTermDebt': 5089000000,
    'DocumentTitleJaHira': 'いんたーなしょなるびじねすましーんずこーぽれーしょん, Public Company',
    'HasESGContent': True,
    'CashAndEquivalents': 13947000000,
    'SalesToAssets': 0.467281,
    'CompanyOfficers': 'Senior Vice President:Erich Clementi |Senior Vice President:Diane J. Gherson |Senior Vice President:Martin J. Schroeter |Senior Vice President:John E. Kelly |Senior Vice President:Michelle H. Browdy |Chief Financial Officer:James J. Kavanaugh |Senior Vice President:Kenneth M. Keverian |Vice President:Robert F. Del Bene |Chairman:Virginia M. Rometty',
    'EquityIndices': '.DJA~DLM~en:DJ COMP AVERAGE|DLM|.DJA~DLM~ja-Hani:DJ コンポジット平均|DLM|.DJA~DLM~zh-Hans:道琼斯综合指数|DLM|.DJI~DLM~en:DOW JONES INDU AVERAGE NDX|DLM|.DJI~DLM~ja-Hani:DJ工業株30種平均指数|DLM|.DJI~DLM~zh-Hans:道琼斯工业平均指数|DLM|.IGX~DLM~en:S&P 500 Growth Index|DLM|.NYA~DLM~en:NYSE COMPOSITE|DLM|.NYA~DLM~ja-Hani:NYSE 総合指数|DLM|.OEXA~DLM~en:S&P 100 INDEX|DLM|.OEXA~DLM~ja-Hani:S&P 100種 指数|DLM|.OEXA~DLM~zh-Hans:标普100指数|DLM|.SPCOMIS~DLM~en:S&P Composite 1500 Software&Serv(IG)|DLM|.SPCOMITCS~DLM~en:S&P 1500 IT Services (Ind)|DLM|.SPCOMTKCS~DLM~en:S&P 1500 ITConsulting&Other Serv(SI)|DLM|.SPCOMT~DLM~en:S&P 1500 Info Technology (Sector)|DLM|.SPLGMID~DLM~en:S&P 900 INDEX|DLM|.SPLRCIS~DLM~en:S&P 500 Software & Services (IG)|DLM|.SPLRCITCS~DLM~en:S&P 500 IT Services (Industry)|DLM|.SPLRCTKCS~DLM~en:S&P 500 IT Consulting&Other Serv(SI)|DLM|.SPLRCT~DLM~en:S&P 500 Information Tech(Sector)|DLM|.SPLRCT~DLM~ja-Hani:S&P 500種 情報技術セクター指数|DLM|.SPLRCT~DLM~zh-Hans:标普信息技术指数|DLM|.SPSUP~DLM~en:S&P Composite 1500 Index|DLM|.SPX~DLM~en:S&P 500 INDEX|DLM|.SPX~DLM~ja-Hani:S&P 500 指数|DLM|.SPX~DLM~zh-Hans:标普500指数|DLM|.TRESGQ1~DLM~en:FTSE IX GL ESG Equal Weighted PR|DLM|.TRX500USP~DLM~en:FR United States 500 Price Return Index|DLM|.TRX50USP~DLM~en:FR United States 50 Price Return Index|DLM|.TRXFLDAAPU~DLM~en:FR Americas Price Return Index|DLM|.TRXFLDAATL~DLM~en:FR Americas Total Return Local Currency Index|DLM|.TRXFLDG7PUSVIT~DLM~en:FR G7 IT Services & Consulting Price Return Index|DLM|.TRXFLDG7PUT21~DLM~en:FR G7 Software & IT Services-572010 Price Return Index|DLM|.TRXFLDG7PUT2~DLM~en:FR G7 Software & IT Services-5720 Price Return Index|DLM|.TRXFLDG7PUTEC~DLM~en:FR G7 Technology Price Return Index|DLM|.TRXFLDG7PU~DLM~en:FR G7 Price Return Index|DLM|.TRXFLDGAPUUSD~DLM~en:FR Global AUD Price Return Index (USD)|DLM|.TRXFLDGAPU~DLM~en:FR Global AUD Price Return Index  (AUD)|DLM|.TRXFLDGATUUSD~DLM~en:FR Global AUD Total Return Index (USD)|DLM|.TRXFLDGDPUSVIT~DLM~en:FR Global Developed IT Services & Consulting Price Return Index|DLM|.TRXFLDGDPUT21~DLM~en:FR Global Developed Software & IT Services-572010 Price Return Index|DLM|.TRXFLDGDPUT2~DLM~en:FR Global Developed Software & IT Services-5720 Price Return Index|DLM|.TRXFLDGDPUTEC~DLM~en:FR Global Developed Technology Price Return Index|DLM|.TRXFLDGDPU~DLM~en:FR Global Developed Price Return Index|DLM|.TRXFLDGFPU~DLM~en:FR Global Ex Frontier Large and Mid Cap Price Return Index (USD)|DLM|.TRXFLDGLPUSVIT~DLM~en:FR Global IT Services & Consulting Price Return Index|DLM|.TRXFLDGLPUT21~DLM~en:FR Global Software & IT Services-572010 Price Return Index|DLM|.TRXFLDGLPUT2~DLM~en:FR Global Software & IT Services-5720 Price Return Index|DLM|.TRXFLDGLPUTEC~DLM~en:FR Global Technology Price Return Index|DLM|.TRXFLDGLPU~DLM~en:FR Global Price Return Index|DLM|.TRXFLDGLTL~DLM~en:FR Global Total Return Local Currency Index|DLM|.TRXFLDGSPUUSD~DLM~en:FR Global Developed Ex Australia Price Return Index (USD)|DLM|.TRXFLDGSPU~DLM~en:FR Global Developed Ex Australia Price Return Index (AUD)|DLM|.TRXFLDGSTUUSD~DLM~en:FR Global Developed Ex Australia Total Return Index (USD)|DLM|.TRXFLDNAPUSVIT~DLM~en:FR North America IT Services & Consulting Price Return Index|DLM|.TRXFLDNAPUT21~DLM~en:FR North America Software & IT Services-572010 Price Return Index|DLM|.TRXFLDNAPUT2~DLM~en:FR North America Software & IT Services-5720 Price Return Index|DLM|.TRXFLDNAPUTEC~DLM~en:FR North America Technology Price Return Index|DLM|.TRXFLDNAPU~DLM~en:FR North America Price Return Index|DLM|.TRXFLDNFPUSVIT~DLM~en:FR NAFTA IT Services & Consulting Price Return Index|DLM|.TRXFLDNFPUT21~DLM~en:FR NAFTA Software & IT Services-572010 Price Return Index|DLM|.TRXFLDNFPUT2~DLM~en:FR NAFTA Software & IT Services-5720 Price Return Index|DLM|.TRXFLDNFPUTEC~DLM~en:FR NAFTA Technology Price Return Index|DLM|.TRXFLDNFPU~DLM~en:FR NAFTA Price Return Index|DLM|.TRXFLDUSPSVIT~DLM~en:FR United States IT Services & Consulting Price Return Index|DLM|.TRXFLDUSPT21~DLM~en:FR United States Software & IT Services-572010 Price Return Index|DLM|.TRXFLDUSPT2~DLM~en:FR United States Software & IT Services-5720 Price Return Index|DLM|.TRXFLDUSPTEC~DLM~en:FR United States Technology Price Return Index|DLM|.TRXFLDUSP~DLM~en:FR United States Price Return Index|DLM|.TRXUSPCA~DLM~en:FR StarMine Combined Alpha United States Index|DLM|.XCI~DLM~en:ARCA COMPUT TECH|DLM|.XII~DLM~en:ARCAINSTITUTIONL',
    'RevenueUsd': 67535000000,
    'DebtToAssets': 0.784435,
    'ShareholdersEquityUsd': 32647000000,
    'RCSOriginalAccountsCurrencyLeafML': 'ja 米ドル|zh-Hans 美元|zh-Hant 美元',
    'CdsUltimateParentCount': 0,
    'AddressStateProvince': 'NEW YORK',
    'CompositeDescriptiveNameJa': 'インターナショナル･ビジネス･マシーンズ･コーポレーション インターナショナルビジネスマシーンズコーポレーション いんたーなしょなるびじねすましーんずこーぽれーしょん インターナショナル・ビジネス・マシーンズ',
    'BusinessDescription': 'International Business Machines Corporation is a provider of global hybrid cloud and artificial intelligence (AI) and consulting expertise. The Company’s segments include Software, Consulting, Infrastructure and Financing. The Software segment includes hybrid cloud and AI platforms, which allow clients to realize their digital and AI transformations across the applications, data, and environments in which they operate. The Consulting segment focuses on integrating skills on strategy, experience, technology and operations by domain and industry. The Infrastructure segment is focused on the hybrid cloud infrastructure market, providing on-premises and cloud-based server and storage solutions. In addition, it offers a portfolio of life-cycle services for hybrid cloud infrastructure deployment. The Financing segment provides client and commercial financing, facilitating its clients’ acquisition of hardware, software and services. It helps clients in more than 175 countries.',
    'ParentOrganisationOrgid': '18228',
    'TotalLiabilities': 119140000000,
    'Rota': 7.328709,
    'BondsCount': 60,
    'SearchTypeBase': 1,
    'QuickRatio': 0.924104,
    'IsShariahCompliant': False,
    'RCSOrganisationSubTypeName': 'OA Organization Subtype\\Company',
    'BusinessEntity': 'ORGANISATION',
    'SicSchemeCode': '8742',
    'ICBSchemeName': 'Technology/Technology/Software & Computer Services/Computer Services',
    'SPsRatingNameX1XSPsRatingType': "Issuer/Standard & Poor's Bond Rating ServicesX1XS&P/S&P Long-term Issuer RatingX1XSPI|Issuer/Standard & Poor's Bond Rating ServicesX1XS&P/S&P Senior UnsecuredX1XSSU|Issuer/Standard & Poor's Bond Rating ServicesX1XS&P/S&P Short-term Issuer Credit RatingX1XSIS|Issuer/Standard & Poor's Bond Rating ServicesX1XS&P/S&P Short-term Issuer Credit RatingX1XSIS|Issuer/Standard & Poor's Bond Rating ServicesX1XS&P/S&P Commercial PaperX1XSCP|Issuer/Standard & Poor's Bond Rating ServicesX1XS&P/S&P Commercial PaperX1XSCP|Issuer/Standard & Poor's Bond Rating ServicesX1XS&P/S&P Senior UnsecuredX1XSSU|Issuer/Standard & Poor's Bond Rating ServicesX1XS&P/S&P Long-term Issuer RatingX1XSPI|Issuer/Standard & Poor's Bond Rating ServicesX1XS&P/S&P Long-term Senior Unsecured MTN RatingX1XSMU|Issuer/Standard & Poor's Bond Rating ServicesX1XS&P/S&P Long-term Senior Unsecured MTN RatingX1XSMU",
    'RatingX1XRatingRankForeign': 'FDS/F1X1X2|FDL/A-X1X7|MSU/A3X1X7|MIS/A3X1X7|EJC/A1X1X2|FCP/WDX1X98|FSS/WDX1X98|MMU/WRX1X98|MCP/P-2X1X2|FSU/A-X1X7|MDL/A3X1X7|EJU/BBB+X1X8|MRS/P-2X1X2|FIS/WDX1X98',
    'PrimaryRICRICAcctsCount': 1675,
    'NetProfit': 10592000000,
    'Ebit': 9632000000,
    'SubsidiariesBondsCount': 7,
    'PretaxProfitInterim': 4143000000,
    'PrimaryRIC': 'IBM',
    'RatingX1XRatingScopeRank': 'EJC/DX1X1|FDS/FX1X2|FDL/FX1X2|MIS/DX1X1|MSU/FX1X2|MIS/FX1X2|MDL/DX1X1|EJC/FX1X2|FSU/DX1X1|FCP/FX1X2|FSS/FX1X2|FCP/DX1X1|FDT/DX1X1|FMU/DX1X1|MMU/FX1X2|MCP/DX1X1|MCP/FX1X2|FSU/FX1X2|MDL/FX1X2|EJU/FX1X2|MSU/DX1X1|EJU/DX1X1|MRS/FX1X2|FIS/FX1X2|MMU/DX1X1',
    'LongTermDebt': 49884000000,
    'CertificatesOfDepositCount': 0,
    'Source': 'NDA',
    'CurrentAssets': 34482000000,
    'CompositeIdentifyingCode': 'VGRQXHF3J8VDLUA7XE92 001368083|1368083 US4592001014 0000051143 4295904307 459200101 001368083 1368083 49EB20 IBM',
    'SPsRatingPreliminary': 'SPI/n|SSU/n|SIS/n|SIS/n|SCP/n|SCP/n|SSU/n|SPI/n|SMU/n|SMU/n',
    'ImpliedVolatilityRIC': '<a:Rship name="x" xmlns:a="http://www.reuters.com/ns/2007/10/31/webservices/SearchAndNavigation_1/NavCommonResponse_1"><a:Entity><a:Prop name="RIC" value="IBMATMIV.U"/><a:Req value="6410" scheme="IDN"/><a:Req value="4018" scheme="IDN"/></a:Entity></a:Rship>',
    'InsertDateTime': '2025-11-01T23:38:46.000Z',
    'DocDateTime': '2026-03-13T10:00:01.824Z',
    'RatingType': 'Issuer/EGJ/EJC|Issuer/FTC/FDS|Issuer/FTC/FDL|Issuer/MDY/MIS|Issuer/MDY/MSU|Issuer/MDY/MIS|Issuer/MDY/MDL|Issuer/EGJ/EJC|Issuer/FTC/FSU|Issuer/FTC/FCP|Issuer/FTC/FSS|Issuer/FTC/FCP|Issuer/FTC/FDT|Issuer/FTC/FMU|Issuer/MDY/MMU|Issuer/MDY/MCP|Issuer/MDY/MCP|Issuer/FTC/FSU|Issuer/MDY/MDL|Issuer/EGJ/EJU|Issuer/MDY/MSU|Issuer/EGJ/EJU|Issuer/MDY/MRS|Issuer/FTC/FIS|Issuer/MDY/MMU',
    'TRBCPrimaryCode': '173',
    'RCSFilingCountryNameML': 'ja 国際機関\\\\米国|zh-Hans 国家分组\\\\美国|zh-Hant 國家分組\\\\美國|de \\\\Vereinigte Staaten|es \\\\Estados Unidos|fr \\\\États Unis|ko \\\\미국|ru \\\\США|ja 国際機関\\\\米国|zh-Hans 国家分组\\北大西洋公约组织\\美国|zh-Hant 國家分組\\北大西洋公約組織\\美國|de \\\\Vereinigte Staaten|es \\\\Estados Unidos|fr \\\\États Unis|ko \\\\미국|ru \\\\США|es Continentes/regiones\\Continente Americano\\Norteamérica\\Estados Unidos|fr Continents/Régions\\Amérique\\Amérique du Nord\\États Unis|ja 大陸 / 地域\\北米 & 中南米\\北米\\米国|ru Континенты/регионы\\Америка\\Северная Америка\\США|zh-Hans 大陆/地区\\美洲\\北美\\美国|zh-Hant 大陸/地區\\美洲\\北美\\美國|de \\Amerika\\Nord-Amerika\\Vereinigte Staaten|ko \\미주\\북아메리카\\미국|ja 国際機関\\\\米国|zh-Hans 国家分组\\亚太经济合作组织\\美国|zh-Hant 國家分組\\亞太經濟合作組織\\美國|de \\\\Vereinigte Staaten|es \\\\Estados Unidos|fr \\\\États Unis|ko \\\\미국|ru \\\\США|ja 国際機関\\\\米国|zh-Hans 国家分组\\经济合作与发展组织\\美国|zh-Hant 國家分組\\經濟合作與發展組織\\美國|de \\\\Vereinigte Staaten|es \\\\Estados Unidos|fr \\\\États Unis|ko \\\\미국|ru \\\\США|ja 国際機関\\\\米国|zh-Hans 国家分组\\\\美国|zh-Hant 國家分組\\\\美國|de \\\\Vereinigte Staaten|es \\\\Estados Unidos|fr \\\\États Unis|ko \\\\미국|ru \\\\США|ja 国\\米国|zh-Hans 国家/地区\\美国|zh-Hant 國家/地區\\美國|de \\Vereinigte Staaten|es \\Estados Unidos|fr \\États Unis|ko \\미국|ru \\США|ja 国際機関\\\\米国|zh-Hans 国家分组\\\\美国|zh-Hant 國家分組\\\\美國|de \\\\Vereinigte Staaten|es \\\\Estados Unidos|fr \\\\États Unis|ko \\\\미국|ru \\\\США|ja EUC 地域\\グローバル\\北米\\米国|zh-Hans EUC 区域\\全球\\北美\\美国|zh-Hant EUC 區域\\全球\\北美\\美國|de \\\\Nord-Amerika\\Vereinigte Staaten|es \\\\\\Estados Unidos|fr \\\\\\États Unis|ko \\\\\\미국|ru \\\\\\США|ja 国際機関\\\\米国|zh-Hans 国家分组\\G10 集团\\美国|zh-Hant 國家分組\\G10 集團\\美國|de \\\\Vereinigte Staaten|es \\\\Estados Unidos|fr \\\\États Unis|ko \\\\미국|ru \\\\США|ja 国際機関\\北米\\米国|zh-Hans 国家分组\\北美\\美国|zh-Hant 國家分組\\北美\\美國|de \\Nord-Amerika\\Vereinigte Staaten|es \\\\Estados Unidos|fr \\\\États Unis|ko \\\\미국|ru \\\\США',
    'RCSCountryOfIncorporationGenealogy': 'M:DQ\\G:AM\\G:6J|M:DQ\\G:AN\\G:6J|M:DH\\G:4\\G:9\\G:6J|M:DQ\\G:AQ\\G:6J|M:DQ\\G:AR\\G:6J|M:DQ\\G:AS\\G:6J|M:A9\\G:6J|M:DQ\\G:B9\\G:6J|M:1M2\\G:3U8\\G:3U9\\G:6J|M:DQ\\G:CX\\G:6J|M:DQ\\G:DE\\G:6J',
    'PrimaryRICRICUsageCount': 3400,
    'SPsRatingRank': 'SPI/7|SSU/7|SIS/3|SIS/3|SCP/3|SCP/3|SSU/7|SPI/7|SMU/0|SMU/7',
    'BuildDateTime': '2026-03-13T09:36:00.925Z',
    'PrimaryRICISIN': 'US4592001014',
    'Roe': 32.444022,
    'HasTRFOS': True,
    'SucceededCompanyPrimaryRIC': 'KNXA.K^L12',
    'SPsRatingX1XSPsRatingRankForeign': 'SSU/A-X1X7|SIS/A-2X1X3|SCP/A-2X1X3|SPI/A-X1X7|SMU/NRX1X0',
    'DocumentTitle': 'International Business Machines Corp, Public Company',
    'RCSCountryHeadquartersNameML': 'ja 国際機関\\\\米国|zh-Hans 国家分组\\\\美国|zh-Hant 國家分組\\\\美國|de \\\\Vereinigte Staaten|es \\\\Estados Unidos|fr \\\\États Unis|ko \\\\미국|ru \\\\США|ja 国際機関\\\\米国|zh-Hans 国家分组\\北大西洋公约组织\\美国|zh-Hant 國家分組\\北大西洋公約組織\\美國|de \\\\Vereinigte Staaten|es \\\\Estados Unidos|fr \\\\États Unis|ko \\\\미국|ru \\\\США|es Continentes/regiones\\Continente Americano\\Norteamérica\\Estados Unidos|fr Continents/Régions\\Amérique\\Amérique du Nord\\États Unis|ja 大陸 / 地域\\北米 & 中南米\\北米\\米国|ru Континенты/регионы\\Америка\\Северная Америка\\США|zh-Hans 大陆/地区\\美洲\\北美\\美国|zh-Hant 大陸/地區\\美洲\\北美\\美國|de \\Amerika\\Nord-Amerika\\Vereinigte Staaten|ko \\미주\\북아메리카\\미국|ja 国際機関\\\\米国|zh-Hans 国家分组\\亚太经济合作组织\\美国|zh-Hant 國家分組\\亞太經濟合作組織\\美國|de \\\\Vereinigte Staaten|es \\\\Estados Unidos|fr \\\\États Unis|ko \\\\미국|ru \\\\США|ja 国際機関\\\\米国|zh-Hans 国家分组\\经济合作与发展组织\\美国|zh-Hant 國家分組\\經濟合作與發展組織\\美國|de \\\\Vereinigte Staaten|es \\\\Estados Unidos|fr \\\\États Unis|ko \\\\미국|ru \\\\США|ja 国際機関\\\\米国|zh-Hans 国家分组\\\\美国|zh-Hant 國家分組\\\\美國|de \\\\Vereinigte Staaten|es \\\\Estados Unidos|fr \\\\États Unis|ko \\\\미국|ru \\\\США|ja 国\\米国|zh-Hans 国家/地区\\美国|zh-Hant 國家/地區\\美國|de \\Vereinigte Staaten|es \\Estados Unidos|fr \\États Unis|ko \\미국|ru \\США|ja 国際機関\\\\米国|zh-Hans 国家分组\\\\美国|zh-Hant 國家分組\\\\美國|de \\\\Vereinigte Staaten|es \\\\Estados Unidos|fr \\\\États Unis|ko \\\\미국|ru \\\\США|ja EUC 地域\\グローバル\\北米\\米国|zh-Hans EUC 区域\\全球\\北美\\美国|zh-Hant EUC 區域\\全球\\北美\\美國|de \\\\Nord-Amerika\\Vereinigte Staaten|es \\\\\\Estados Unidos|fr \\\\\\États Unis|ko \\\\\\미국|ru \\\\\\США|ja 国際機関\\\\米国|zh-Hans 国家分组\\G10 集团\\美国|zh-Hant 國家分組\\G10 集團\\美國|de \\\\Vereinigte Staaten|es \\\\Estados Unidos|fr \\\\États Unis|ko \\\\미국|ru \\\\США|ja 国際機関\\北米\\米国|zh-Hans 国家分组\\北美\\美国|zh-Hant 國家分組\\北美\\美國|de \\Nord-Amerika\\Vereinigte Staaten|es \\\\Estados Unidos|fr \\\\États Unis|ko \\\\미국|ru \\\\США',
    'RCSOrganisationSubTypeLeafML': 'ja 法人|zh-Hans 公司',
    'DocumentTitleJaHani': 'インターナショナル･ビジネス･マシーンズ･コーポレーション, Public Company',
    'ReutersIndustryClassification': 'Data Processing & Reproduction',
    'LocalScheme': 'Industrial|Information Technology/Information Technology Hardware|Industrials/Computer Hardware',
    'CountryHeadquarters': 'USA',
    'GeneralAliasName': 'TRINTEX|Big Blue|Guo Ji Shang Ye Ji Qi Gong Si|Guo Ji Shang Yong Ji Qi|IBM|Intanashonaru Bijinesu Mashinzu|International Business Machines|International Business Machines Corp|Software Artistry Inc|Unison Software Inc',
    'IsContributor': False,
    'IsMainCompanyFiling': True,
    'OptionsCount': 2374,
    'RCSTRBC2012NameML': 'ja テクノロジー\\ソフトウェア & IT サービス\\ソフトウェア & IT サービス\\IT サービス & コンサルティング\\IT サービス & コンサルティング (その他)|zh-Hans 技术\\软件及信息技术服务\\软件及信息技术服务\\信息技术服务及咨询\\IT 服务及咨询 (其他 (NEC))|zh-Hant 技術\\軟體及信息技術服務\\軟體及信息技術服務\\信息技術服務及諮詢\\IT 服務及諮詢 (其他 (NEC))',
    'HKVersion': '0',
    'ParentCompanyOAPermID': '4295904307',
    'RCSOrganisationSubType': 'OAOST:COR',
    'PretaxProfit': 10328000000,
    'OrganizationWebsite': 'https://www.ibm.com/',
    'GeneralAliasNameZhHant': '國際商業機器公司',
    'CDS5YSuperRIC': '<a:Rship name="x" xmlns:a="http://www.reuters.com/ns/2007/10/31/webservices/SearchAndNavigation_1/NavCommonResponse_1"><a:Entity rank="1"><a:Prop name="RIC" value="IBM5YUSAX="/><a:Prop name="DisplayName" value="IBM" lang="en"/><a:Req value="6995" scheme="IDN"/></a:Entity></a:Rship>',
    'ShareholdersEquity': 32647000000,
    'IssuerHasCds': True,
    'FtseScheme': 'Information Technology/Software & Computer Services/Computer Services',
    'RCSPartyCountryLeaf': 'United States',
    'DTSubjectName': 'International Business Machines Corp',
    'RCSTRBCNameML': 'ja テクノロジー\\ソフトウェア & IT サービス\\ソフトウェア & IT サービス\\IT サービス & コンサルティング|zh-Hans 技术\\软件及信息技术服务\\软件及信息技术服务\\信息技术服务及咨询|zh-Hant 技術\\軟體及信息技術服務\\軟體及信息技術服務\\信息技術服務及諮詢',
    'PretaxProfitMargin': 0.152928,
    'RCSTRBCGenealogy': 'B:161\\B:171\\B:172\\B:173',
    'IssuerBondsExist': True,
    'CommercialPaperCount': 0,
    'RatingRank': 'EJC/2|FDS/2|FDL/7|MIS/7|MSU/7|MIS/7|MDL/7|EJC/2|FSU/7|FCP/98|FSS/98|FCP/2|FDT/98|FMU/98|MMU/98|MCP/2|MCP/2|FSU/7|MDL/7|EJU/8|MSU/7|EJU/8|MRS/2|FIS/98|MMU/98',
    'InterimNetIncome': 5599000000,
    'NAVPrimaryRIC': '<a:Rship name="x" xmlns:a="http://www.reuters.com/ns/2007/10/31/webservices/SearchAndNavigation_1/NavCommonResponse_1"><a:Entity><a:Prop name="RIC" value="IBM"/><a:Req value="62" scheme="IDN"/><a:Req value="6216" scheme="IDN"/></a:Entity></a:Rship>',
    '_UID': 3768672253,
    'UltimateParentOrganizationID': '4295904307',
    'ActiveEstimatesExist': True,
    'PretaxProfitUsd': 10328000000,
    'RatingsScope': [{'Agency': 'EGJ',
      'CurrentRatingDate': '2018-11-02T00:00:00.000Z',
      'RatingType': 'EJC',
      'CurrentRatingRank': 2,
      'CurrentRating': 'A1',
      'Preliminary': 'n',
      'RatingScope': 'D',
      'Solicited': 'y'},
     {'Agency': 'FTC',
      'CurrentRatingDate': '2023-11-29T00:00:00.000Z',
      'RatingType': 'FDS',
      'CurrentRatingRank': 2,
      'CurrentRating': 'F1',
      'Preliminary': 'n',
      'RatingScope': 'F',
      'Solicited': 'y'},
     {'CurrentRating': 'A-',
      'Agency': 'FTC',
      'CurrentRatingDate': '2023-11-29T00:00:00.000Z',
      'OutlookRank': 0,
      'RatingType': 'FDL',
      'CurrentRatingRank': 7,
      'Outlook': 'Rating Outlook Stable',
      'Preliminary': 'n',
      'RatingScope': 'F',
      'Solicited': 'y'},
     {'Agency': 'MDY',
      'CurrentRatingDate': '2021-10-14T00:00:00.000Z',
      'RatingType': 'MIS',
      'CurrentRatingRank': 7,
      'CurrentRating': 'A3',
      'Preliminary': 'n',
      'RatingScope': 'D',
      'Solicited': 'y'},
     {'Agency': 'MDY',
      'CurrentRatingDate': '2021-10-14T00:00:00.000Z',
      'RatingType': 'MSU',
      'CurrentRatingRank': 7,
      'CurrentRating': 'A3',
      'Preliminary': 'n',
      'RatingScope': 'F',
      'Solicited': 'y'},
     {'Agency': 'MDY',
      'CurrentRatingDate': '2021-10-14T00:00:00.000Z',
      'RatingType': 'MIS',
      'CurrentRatingRank': 7,
      'CurrentRating': 'A3',
      'Preliminary': 'n',
      'RatingScope': 'F',
      'Solicited': 'y'},
     {'CurrentRating': 'A3',
      'Agency': 'MDY',
      'CurrentRatingDate': '2026-01-29T00:00:00.000Z',
      'OutlookRank': 0,
      'RatingType': 'MDL',
      'CurrentRatingRank': 7,
      'Outlook': 'Stable',

#### Understanding values using Navigators
Using the output from a debugging session, there are a number of common properties that are very useful when filtering your search.  For example, you may want to filter your results based on a specific category of data.  Using navigators will help us understand these categories.

> Note: You can find more details and examples within the 'Search - Navigators' notebook.

Looking at our debug output above, one useful property: **SearchAllCategoryv3** will helps us understand all available categories of documents the query term 'IBM' was found.  To list these categories, use the following:

In [29]:
response=search.Definition(
    query = "IBM",
    top = 0,
    navigators = "SearchAllCategoryv3"
).get_data()
response.data.raw["Navigators"]["SearchAllCategoryv3"]["Buckets"]

[{'Label': 'Other Quote', 'Count': 22290},
 {'Label': 'Warrants', 'Count': 5835},
 {'Label': 'Bond Pricing', 'Count': 3369},
 {'Label': 'Options', 'Count': 2396},
 {'Label': 'Bonds', 'Count': 2283},
 {'Label': 'Commercial Papers', 'Count': 1315},
 {'Label': 'Companies/Issuers', 'Count': 876},
 {'Label': 'Futures', 'Count': 843},
 {'Label': 'Mergers & Acquisitions', 'Count': 802},
 {'Label': 'Equities', 'Count': 724},
 {'Label': 'Other Instrument', 'Count': 680},
 {'Label': 'Credit Default Swaps', 'Count': 313},
 {'Label': 'Officers', 'Count': 285},
 {'Label': 'Analyst', 'Count': 250},
 {'Label': 'Fixed Income Curves', 'Count': 64},
 {'Label': 'FX & Money', 'Count': 63},
 {'Label': 'Help Videos', 'Count': 14},
 {'Label': 'Funds', 'Count': 12},
 {'Label': 'Mortgage Backed Securities', 'Count': 12},
 {'Label': 'Commodities', 'Count': 8},
 {'Label': 'People', 'Count': 7},
 {'Label': 'Buy Side Contact', 'Count': 6},
 {'Label': 'Private Equity / Venture Capital Fund', 'Count': 6},
 {'Label': 'CMO & ABS', 'Count': 5},
 {'Label': 'Fund Manager', 'Count': 4},
 {'Label': 'Loans', 'Count': 4},
 {'Label': 'Commodities Physical Assets', 'Count': 3},
 {'Label': 'Indices', 'Count': 2}]

Using the above listing, we can narrow our result set based on these categories using a Filter.

#### Special Properties
The Search service includes a number of special properties that enhance the ability to find meaningful results. In addition to the special property *_debugall* used within the **select** parameter as outlined above, the following properties are available:

In [30]:
# The 'code' specification will search across all codes, such as RICs, tickers, SEDOLs etc.  
# Primarily used within a filter but can be used as a selectable property.
ld.discovery.search(filter = "code eq 'IBM'")

,BusinessEntity,DocumentTitle,PermID,PI,RIC
0,ORGANISATION,"International Business Machines Corp, Public Company",<NA>,37036,<NA>
1,QUOTExEQUITY,"International Business Machines Corp, Ordinary Share, NYSE Consolidated",55839165994,1097326,IBM
2,QUOTExEQUITY,"International Business Machines Corp, Ordinary Share, MiFID Composite Cross Market Service",21523029548,131770829,IBMEUR.xbo
3,QUOTExEQUITY,"International Business Machines Corp, Depository Receipt, The Toronto Stock Exchange",236800710566,975665825,IBM.TO
4,QUOTExEQUITY,"International Business Machines Corp, Ordinary Share, New York Stock Exchange",55838323096,1090370,IBM.N
5,QUOTExEQUITY,"International Business Machines Corp, Ordinary Share, NASDAQ INTERMARKET",55835333953,765744,IBM.TH
6,QUOTExEQUITY,"International Business Machines Corp, Ordinary Share, Cboe BZX Exchange",55845629228,53703996,IBM.Z
7,QUOTExEQUITY,"International Business Machines Corp, Ordinary Share, NYSE Arca",55837129318,753753,IBM.P
8,QUOTExEQUITY,"International Business Machines Corp, Ordinary Share, Cboe EDGX Exchange",21475059739,73533774,IBM.DG
9,QUOTExEQUITY,"International Business Machines Corp, Ordinary Share, Frankfurt Stock Exchange",55836444333,722691,IBM.F

In [31]:
# The 'name' specification will search across all names, such as common name, legal name, issuer name, etc. 
# Primarily used within a filter but can be used as a selectable property.
ld.discovery.search(filter = "name eq 'IBM'")

,BusinessEntity,DocumentTitle,PermID,PI,RIC
0,ORGANISATION,"International Business Machines Corp, Public Company",<NA>,37036,<NA>
1,ORGANISATION,"Banco IBM SA, Private Company",<NA>,76208,<NA>
2,QUOTExEQUITY,"International Business Machines Corp, Ordinary Share, NYSE Consolidated",55839165994,1097326,IBM
3,ORGANISATION,"Ibm International Capital Pte Ltd, Private Company",<NA>,43943628,<NA>
4,ORGANISATION,"Banco Plata SA Institucion de Banca Multiple, Private Company",<NA>,51714311,<NA>
5,ORGANISATION,"Tiers Corporate Bond Backed Certificates Trust Series Ibm 1997 4, Private Company",<NA>,18062670,<NA>
6,QUOTExEQUITY,"Eurex IBM Single Stock Dividend Future Chain Contracts, Equity Future, USD, Eurex",21539944402,156524731,0#I2BM:
7,QUOTExEQUITY,"Eurex IBM Single Stock Equity Future Chain Contracts, Equity Future, USD, Eurex",21481052421,48924732,0#IBMF:
8,QUOTExEQUITY,"Euronext Amsterdam IBM Dividend Future Chain Chain Contracts, Equity Future, USD, Euronext Amsterdam",21612423771,259118763,0#IBMDF:
9,QUOTExEQUITY,"Eurex IBM Single Stock Equity Future Continuation 1, Equity Future, USD, Eurex",21481052892,49450681,IBMFc1

In [32]:
# The special character underscore (_) is a convenient token that can be used to select the default Properties.  
# This will allow users to quickly select the default values plus any other properties when testing out your search.
ld.discovery.search(
    query = "IBM",
    top = 1000,
    select = "_, SearchAllCategoryv3"
)

,BusinessEntity,DocumentTitle,PermID,PI,RIC,SearchAllCategoryv3
0,ORGANISATION,"International Business Machines Corp, Public Company",<NA>,37036,<NA>,Companies/Issuers
1,ORGANISATION,"Banco IBM SA, Private Company",<NA>,76208,<NA>,Companies/Issuers
2,QUOTExEQUITY,"International Business Machines Corp, Ordinary Share, NYSE Consolidated",55839165994,1097326,IBM,Equities
3,ORGANISATION,"Ibm International Capital Pte Ltd, Private Company",<NA>,43943628,<NA>,Companies/Issuers
4,ORGANISATION,"Banco Plata SA Institucion de Banca Multiple, Private Company",<NA>,51714311,<NA>,Companies/Issuers
...,...,...,...,...,...,...
995,QUOTExEQUITY,"OPRA International Business Machines Equity Option 290 Call Jan 2027 , Equity Cash Option, Call 290 USD 15-Jan-2027, OPRA",22058828188,831047632,IBMA152729000.U,Options
996,QUOTExEQUITY,"OPRA International Business Machines Equity Option 180 Call Apr 2026 , Equity Cash Option, Call 180 USD 10-Apr-2026, OPRA",22162211579,998881977,IBMD102618000.U,Options
997,QUOTExEQUITY,"OPRA International Business Machines Equity Option 320 Put Mar 2026 , Equity Cash Option, Put 320 USD 13-Mar-2026, OPRA",22156036588,988359321,IBMO132632000.U,Options
998,QUOTExEQUITY,"OPRA International Business Machines Equity Option 420 Put Mar 2026 , Equity Cash Option, Put 420 USD 20-Mar-2026, OPRA",22111094885,914775030,IBMO202642000.U,Options
999,QUOTExEQUITY,"OPRA International Business Machines Equity Option 390 Call Mar 2026 , Equity Cash Option, Call 390 USD 13-Mar-2026, OPRA",22156415721,988967568,IBMC132639000.U,Options

#### Common Properties
As you become more familiar with search, you will soon recognize there will be a number of very useful properties that will act as your "go-tos" when filtering or selecting fields.

In [33]:
# DocumentTitle
# As you've seen in some of the above output, this property is on by default when you want to display your search results.  
# The DocumentTitle property is a quick way to describe the content retrieved for each matching document.  
# It is made up of the following child properties: 
#    'DTSubjectName', 'DTSimpleType', 'DTSource', and 'DTCharacteristics'.
ld.discovery.search(
    query = "IBM",
    top = 100,
    select = "DocumentTitle, DTSubjectName, DTSimpleType, DTSource, DTCharacteristics"
)

,DocumentTitle,DTSubjectName,DTSimpleType,DTSource,DTCharacteristics
0,"International Business Machines Corp, Public Company",International Business Machines Corp,Public Company,<NA>,<NA>
1,"Banco IBM SA, Private Company",Banco IBM SA,Private Company,<NA>,<NA>
2,"International Business Machines Corp, Ordinary Share, NYSE Consolidated",International Business Machines Corp,Ordinary Share,NYSE Consolidated,<NA>
3,"Ibm International Capital Pte Ltd, Private Company",Ibm International Capital Pte Ltd,Private Company,<NA>,<NA>
4,"Banco Plata SA Institucion de Banca Multiple, Private Company",Banco Plata SA Institucion de Banca Multiple,Private Company,<NA>,<NA>
...,...,...,...,...,...
95,"OPRA International Business Machines Equity Option 235 Call Mar 2026 , Equity Cash Option, Call 235 USD 13-Mar-2026, OPRA",OPRA International Business Machines Equity Option 235 Call Mar 2026,Equity Cash Option,OPRA,Call 235 USD 13-Mar-2026
96,"OPRA International Business Machines Equity Option 240 Put Mar 2026 , Equity Cash Option, Put 240 USD 13-Mar-2026, OPRA",OPRA International Business Machines Equity Option 240 Put Mar 2026,Equity Cash Option,OPRA,Put 240 USD 13-Mar-2026
97,"OPRA International Business Machines Equity Option 237.5 Put Mar 2026 , Equity Cash Option, Put 237.5 USD 20-Mar-2026, OPRA",OPRA International Business Machines Equity Option 237.5 Put Mar 2026,Equity Cash Option,OPRA,Put 237.5 USD 20-Mar-2026
98,"OPRA International Business Machines Equity Option 245 Call May 2026 , Equity Cash Option, Call 245 USD 15-May-2026, OPRA",OPRA International Business Machines Equity Option 245 Call May 2026,Equity Cash Option,OPRA,Call 245 USD 15-May-2026
99,"OPRA International Business Machines Equity Option 225 Put May 2026 , Equity Cash Option, Put 225 USD 15-May-2026, OPRA",OPRA International Business Machines Equity Option 225 Put May 2026,Equity Cash Option,OPRA,Put 225 USD 15-May-2026

In [34]:
# SearchAllCategoryv3
# When trying to narrow down your search to specific categories, this property can be extremely useful.  
# When you apply a Navigator on this property, it will return a list of ~40 categories, depending on the view. 
# Categories include asset-related instruments such as:
#     'Equities', 'Futures' , 'Options', 'Bonds', 'Commodities' 
#     but can also include things like: 'People', 'Analyst', 'Officers'.
ld.discovery.search(
    query = "IBM",
    filter = "SearchAllCategoryv3 eq 'People'",
)

  BusinessEntity                 DocumentTitle       PermID           PI
0         PERSON       Tom Cadigan - IsUnknown  34414743082  34414743082
1         PERSON     Robert Ploder - IsUnknown  34414738667  34414738667
2         PERSON   Claudia Barclay - IsUnknown  34414721056  34414721056
3         PERSON  Charlie Maxfield - IsUnknown  34414669683  34414669683
4         PERSON       John Denham - IsUnknown  34414661717  34414661717
5         PERSON  William E. Baker - IsUnknown  34415092341  34415092341
6         PERSON  R. L. Jay Vivian - IsUnknown  34414808510  34414808510

In [38]:
# CodeResolutionBase
# Represents the most significant codes defined within the document.  For example, when searching for a symbol such 
# as ISIN, SEDOL, RIC, etc, filtering against this property will significantly reduce the matches and only bring 
# back the most relevant results.
ld.discovery.search(
    filter = "CodeResolutionBase eq 'US046353AQ14'",
    select = "DocumentTitle, ISIN, SEDOL, RIC, IssuerEquityPrimaryRIC"
)

,DocumentTitle,ISIN,SEDOL,IssuerEquityPrimaryRIC
0,"AstraZeneca PLC, Plain Vanilla Fixed Coupon Bond, TRACE Eligible AZN 2.375 12-Jun-2022",US046353AQ14,BF4SNM7,AZN.L

In [40]:
# Conversely, if we were to choose the more generic term 'code', would result in a wider range of matches.
ld.discovery.search(
    filter = "code eq 'US046353AQ14'",
    select = "DocumentTitle, ISIN, SEDOL, IssuerEquityPrimaryRIC"
)

,DocumentTitle,ISIN,SEDOL,IssuerEquityPrimaryRIC
0,"AstraZeneca PLC, Bond Quote, TRACE Eligible, TRADEWEB DIRECT",<NA>,BF4SNM7,AZN.L
1,"AstraZeneca PLC, Bond Quote, TRACE Eligible, REAL TIME ALL QUOTES",<NA>,BF4SNM7,AZN.L
2,"NT, Note, US046353AQ14 MiFID II Fine Grained RIC, Deutsche Boerse AG APA Service",<NA>,<NA>,<NA>
3,"AstraZeneca PLC, Plain Vanilla Fixed Coupon Bond, TRACE Eligible AZN 2.375 12-Jun-2022",US046353AQ14,BF4SNM7,AZN.L

#### Common Properties - RCS (Reuters Classification Scheme)
Throughout many documents, you will notice a number of RCS fields that are popular when selecting and filtering.

*Note* - I'll use navigators to demonstrate the values of these common properties.

In [41]:
# RCSAssetCategoryLeaf
# Specific to assets, this property will categorize the results into a readable identifier such as: 'Bond', 
# 'Commodity Future', 'Commercial Paper', etc.  Where the property SearchAllCategoryv3 provides general categories, 
# this property will be more specific to assets.  Pull out the top 10.
response = search.Definition(
    top = 0,
    navigators = "RCSAssetCategoryLeaf(buckets:20)"
).get_data()
response.data.raw["Navigators"]["RCSAssetCategoryLeaf"]["Buckets"]

[{'Label': 'Bond', 'Count': 21074604},
 {'Label': 'Barrier Warrant', 'Count': 9093601},
 {'Label': 'Commodity Future', 'Count': 6992418},
 {'Label': 'Interest Rate Future Spread', 'Count': 5444728},
 {'Label': 'Equity Cash Option', 'Count': 5058973},
 {'Label': 'Commodity Spread', 'Count': 3562822},
 {'Label': 'Equity Future', 'Count': 3397071},
 {'Label': 'Warrant', 'Count': 3376713},
 {'Label': 'Certificate of Deposit', 'Count': 3248712},
 {'Label': 'Mortgage-Backed Security', 'Count': 3173332},
 {'Label': 'Commercial Paper', 'Count': 3063071},
 {'Label': 'Traditional Warrant', 'Count': 2972906},
 {'Label': 'Commodity Forward', 'Count': 2769984},
 {'Label': 'Commodity Spot', 'Count': 2280412},
 {'Label': 'Ordinary Share', 'Count': 2154908},
 {'Label': 'Equity Index', 'Count': 1698071},
 {'Label': 'Commodity Future Option', 'Count': 1507912},
 {'Label': 'Open-End Fund', 'Count': 1500173},
 {'Label': 'Mini-Futures Certificate', 'Count': 1304583},
 {'Label': 'Spread', 'Count': 882592}]

In [42]:
# RCSCountryLeaf
# RCSIssuerCountryLeaf
# RCSExchangeCountryLeaf
# Specific to some assets, will allow you to narrow your search to focus on a specific country.  Pull out the top 20.
response = search.Definition(
    top = 0,
    navigators = "RCSCountryLeaf(buckets:20)"
).get_data()
response.data.raw["Navigators"]["RCSCountryLeaf"]["Buckets"]

[{'Label': 'United States', 'Count': 15766746},
 {'Label': 'Eurobond', 'Count': 7100211},
 {'Label': 'Colombia', 'Count': 1513679},
 {'Label': 'China (Mainland)', 'Count': 1479842},
 {'Label': 'South Korea', 'Count': 681661},
 {'Label': 'Canada', 'Count': 627885},
 {'Label': 'Germany', 'Count': 572182},
 {'Label': 'France', 'Count': 345953},
 {'Label': 'India', 'Count': 313067},
 {'Label': 'Australia', 'Count': 201151},
 {'Label': 'Japan', 'Count': 181381},
 {'Label': 'Brazil', 'Count': 152272},
 {'Label': 'Italy', 'Count': 146573},
 {'Label': 'Chile', 'Count': 141972},
 {'Label': 'Switzerland', 'Count': 92385},
 {'Label': 'Norway', 'Count': 79617},
 {'Label': 'United Kingdom', 'Count': 72754},
 {'Label': 'Mexico', 'Count': 72715},
 {'Label': 'Austria', 'Count': 71965},
 {'Label': 'Belgium', 'Count': 70371}]

In [43]:
# RCSCurrencyLeaf
# Specific to some assets, will allow you to narrow your search to focus on a specific currency.  Just pull out the top 20.
response = search.Definition(
    top = 0,
    navigators = "RCSCurrencyLeaf(buckets:20)"
).get_data()
response.data.raw["Navigators"]["RCSCurrencyLeaf"]["Buckets"]

[{'Label': 'US Dollar', 'Count': 45274092},
 {'Label': 'Euro', 'Count': 26615154},
 {'Label': 'Chinese Yuan', 'Count': 3710368},
 {'Label': 'Colombian Peso', 'Count': 1778563},
 {'Label': 'Swedish Krona', 'Count': 1770871},
 {'Label': 'Hong Kong Dollar', 'Count': 1654451},
 {'Label': 'Canadian Dollar', 'Count': 1564253},
 {'Label': 'Japanese Yen', 'Count': 1549161},
 {'Label': 'US Cent', 'Count': 1402045},
 {'Label': 'Indian Rupee', 'Count': 1290196},
 {'Label': 'British Pound', 'Count': 1176845},
 {'Label': 'South Korean Won', 'Count': 1124820},
 {'Label': 'Swiss Franc', 'Count': 797690},
 {'Label': 'British Penny', 'Count': 727014},
 {'Label': 'Australian Dollar', 'Count': 718718},
 {'Label': 'Norwegian Krone', 'Count': 680136},
 {'Label': 'Turkish Lira', 'Count': 564685},
 {'Label': 'Hungarian Forint', 'Count': 528630},
 {'Label': 'Malaysian Ringgit', 'Count': 517044},
 {'Label': 'Brazilian Real', 'Count': 426873}]

In [44]:
# RCSTRBC2012Leaf
# Represents the industry sector.  For example, if I query for Apple Computers, I will get many different industry sectors such as: 
# 'Computer Hardware (NEC)', 'Laptop & Desktop Computers', 'Phones & Smart Phones', etc.
response = search.Definition(
    top = 0,
    navigators = "RCSTRBC2012Leaf(buckets:20)"
).get_data()
response.data.raw["Navigators"]["RCSTRBC2012Leaf"]["Buckets"]

[{'Label': 'Banks (NEC)', 'Count': 7178416},
 {'Label': 'Corporate Financial Services (NEC)', 'Count': 5000726},
 {'Label': 'Corporate Banks', 'Count': 1725131},
 {'Label': 'Investment Banking & Brokerage Services (NEC)', 'Count': 1384069},
 {'Label': 'Investment Holding Companies (NEC)', 'Count': 1233482},
 {'Label': 'Financial & Commodity Market Operators & Service Providers (NEC)',
  'Count': 934769},
 {'Label': 'Business Support Services (NEC)', 'Count': 934468},
 {'Label': 'Construction & Engineering (NEC)', 'Count': 927889},
 {'Label': 'Government & Government Finance (NEC)', 'Count': 898840},
 {'Label': 'Real Estate Rental, Development & Operations (NEC)',
  'Count': 794173},
 {'Label': 'Building Contractors', 'Count': 779540},
 {'Label': 'Investment Banking', 'Count': 684069},
 {'Label': 'Electric Utilities (NEC)', 'Count': 548599},
 {'Label': 'Wealth Management', 'Count': 524600},
 {'Label': 'Management Consulting Services', 'Count': 510016},
 {'Label': 'Public Finance Activities', 'Count': 496840},
 {'Label': 'Consumer Lending (NEC)', 'Count': 458860},
 {'Label': 'Supermarkets & Convenience Stores', 'Count': 437423},
 {'Label': 'Real Estate Services (NEC)', 'Count': 419929},
 {'Label': 'IT Services & Consulting (NEC)', 'Count': 419165}]

In [45]:
# RCSTRBC2012Leaf
# RCSTRBC2012Genealogy
# RCSTRBC2012Name
# Provide a breakdown of the hierarchy defined for many of these RCS attributes.  You can see the mapping between the 
# hierarchy defined with the Genealogy property and Name property.  
# For example, the code 'B:262' maps to the name 'Banking & Investment Services'.
response = search.Definition(
    filter = "RCSTRBC2012Leaf eq 'Banks'",    # Limit the sector to banks so we can easily observe the output below
    top = 0,
    navigators = "RCSTRBC2012Leaf, RCSTRBC2012Genealogy, RCSTRBC2012Name"
).get_data()
response.data.raw

{'Total': 9309950,
 'Hits': [],
 'Navigators': {'RCSTRBC2012Genealogy': {'Buckets': [{'Label': 'B:261\\B:262\\B:127\\B:128\\B:1615',
     'Count': 7178416},
    {'Label': 'B:261\\B:262\\B:127\\B:128\\B:1616', 'Count': 1757142},
    {'Label': 'B:261\\B:262\\B:127\\B:128\\B:1617', 'Count': 313993},
    {'Label': 'B:261\\B:262\\B:127\\B:128\\B:1619', 'Count': 29766},
    {'Label': 'B:261\\B:262\\B:127\\B:131\\B:1629', 'Count': 24492},
    {'Label': 'B:261\\B:262\\B:127\\B:128\\B:1620', 'Count': 4886},
    {'Label': 'B:261\\B:262\\B:263\\B:207\\B:1638', 'Count': 1055},
    {'Label': 'B:261\\B:262\\B:127\\B:128\\B:1618', 'Count': 200}]},
  'RCSTRBC2012Leaf': {'Buckets': [{'Label': 'Banks (NEC)', 'Count': 7178416},
    {'Label': 'Corporate Banks', 'Count': 1757142},
    {'Label': 'Retail & Mortgage Banks', 'Count': 313993},
    {'Label': 'Private Banks', 'Count': 29766},
    {'Label': 'Import-Export Banks', 'Count': 24492},
    {'Label': 'Islamic Banks', 'Count': 4886},
    {'Label': 'Merchant Banks', 'Count': 1055},
    {'Label': 'Money Center Banks', 'Count': 200}]},
  'RCSTRBC2012Name': {'Buckets': [{'Label': 'Financials\\Banking & Investment Services\\Banking Services\\Banks\\Banks (NEC)',
     'Count': 7178416},
    {'Label': 'Financials\\Banking & Investment Services\\Banking Services\\Banks\\Corporate Banks',
     'Count': 1757142},
    {'Label': 'Financials\\Banking & Investment Services\\Banking Services\\Banks\\Retail & Mortgage Banks',
     'Count': 313993},
    {'Label': 'Financials\\Banking & Investment Services\\Banking Services\\Banks\\Private Banks',
     'Count': 29766},
    {'Label': 'Financials\\Banking & Investment Services\\Banking Services\\Corporate Financial Services\\Import-Export Banks',
     'Count': 24492},
    {'Label': 'Financials\\Banking & Investment Services\\Banking Services\\Banks\\Islamic Banks',
     'Count': 4886},
    {'Label': 'Financials\\Banking & Investment Services\\Investment Banking & Investment Services\\Investment Banking & Brokerage Services\\Merchant Banks',
     'Count': 1055},
    {'Label': 'Financials\\Banking & Investment Services\\Banking Services\\Banks\\Money Center Banks',
     'Count': 200}]}}}

The above output includes 3 separate sections: RCSTRBC2012Genealogy, RCSTRBC2012Leaf and RCSTRBC2012Name.  For each you can see a breakdown ot the buckets.

In [46]:
ld.close_session()