## Limits
RDP Search does impose limits on the size of the result set when requesting for large data sets.  The following examples provide some useful techniques when dealing with results reaching the upper limits imposed by the backend.

In [1]:
import lseg.data as ld
from lseg.data.content import search
import pandas as pd

# Default session - desktop
ld.open_session()

In [2]:
pd.set_option('display.max_colwidth', 140)
ld.__version__

'2.1.1'

#### Grouping
There may be instances where the result set contains groups of values for properties based on your request.  For example, if I'm interested in retrieving all exchanges within the USA, I can execute this request:

In [3]:
response = search.Definition(
    view = search.Views.EQUITY_QUOTES,
    filter = "RCSExchangeCountryLeaf eq 'United States'",
    top = 10000,
    select = "ExchangeCode, RIC"
).get_data()
response.total

C:\Users\nzincone\AppData\Roaming\Python\Python312\site-packages\lseg\data\content\search\_data_provider.py:298:UserWarning: Search result for None not full.
Result is maxed at 10000 while the total is 4869136 rows.
Requested - 10000, skipped - 0 rows.

4869136

In [4]:
response.data.df

     ExchangeCode       RIC
0             IOM      ESv1
1             IOM     EScv1
2             IOM      ESc1
3             IOM     NQcv1
4             IOM      NQc1
...           ...       ...
9995          PNK   SWRI.PK
9996          PNK  OCESP.PK
9997          PNK   MPEG.PK
9998          PNK   NILA.PK
9999          PNK  CENBF.PK

[10000 rows x 2 columns]

In the above example, you can see the total available documents is close to 5 million hits and as a result, a warning is issued.  However, due to the nature of the data set, the exchange codes have been repeated which brought back the upper limit of documents within the result set.  **Note**: At the time of this writing, the upper limit has been defined as 10000 result sets.

Instead of performing multiple calls and pulling out the unique codes within each result set, I can apply the <b>group_by</b> feature offered by Search to significantly reduce the result set returned.  For example:

In [5]:
ld.discovery.search(
    view = search.Views.EQUITY_QUOTES,
    filter = "RCSExchangeCountryLeaf eq 'United States'",
    top = 10000,
    select = "ExchangeCode",
    group_by = "ExchangeCode",    # Exchange codes can be grouped
    group_count = 1               # Then limited to 1 for each to create uniqueness
)

    ExchangeCode
0            IOM
1            NSQ
2            NYQ
3            NMQ
4            NAQ
..           ...
153          CC3
154          CCE
155          CSC
156          HAM
157          MDE

[158 rows x 1 columns]

Grouping the results, I've significantly reduced the hit count using a single API call.  Using the <b>group_by</b> technique to pull out the unique exchange codes is very useful if you wish to return many other properties as part of your results.  However, if you are strictly after the list of exchange codes, the preferred approach is to use Navigators.

#### Navigators
If the goal of your search is to simply capture the taxonomy of exchange codes, then the preferred approach in this case is to use Navigators.  A navigator allows the ability to categorize and summarize properties within the result set.  For example, I can provide a simple navigator where I can limit the number of buckets, or results, within the result set.

> Note: You can find more details and examples within the 'Search - Navigators' notebook.

You can do this using the following request:

In [ ]:
# Issue the request.
# Note: Navigators returned within a separate result set. No need to specify a <b>top</b> value.
response=search.Definition(
    view = search.Views.EQUITY_QUOTES,
    filter = "RCSExchangeCountryLeaf eq 'United States'",
    top = 0,   # Set to 0 to return no results but still get the navigator buckets
    navigators = "ExchangeCode(buckets:50)"   # Limit the results to the top 50
).get_data()

In [10]:
# Present the output...
codes=response.data.raw["Navigators"]["ExchangeCode"]["Buckets"]
print(f'Total exchange codes found: {len(codes)}')

Total exchange codes found: 50

In [11]:
codes

[{'Label': 'OPQ', 'Count': 1992423},
 {'Label': 'ONE', 'Count': 1437314},
 {'Label': 'IOM', 'Count': 381700},
 {'Label': 'CME', 'Count': 135003},
 {'Label': 'PNK', 'Count': 76142},
 {'Label': 'NAS', 'Count': 61833},
 {'Label': 'CBO', 'Count': 56986},
 {'Label': 'OBB', 'Count': 32907},
 {'Label': 'OTC', 'Count': 30527},
 {'Label': 'IUS', 'Count': 25723},
 {'Label': 'CBT', 'Count': 25718},
 {'Label': 'BOS', 'Count': 19713},
 {'Label': 'THM', 'Count': 19366},
 {'Label': 'GTC', 'Count': 18163},
 {'Label': 'XPH', 'Count': 17075},
 {'Label': 'MID', 'Count': 16001},
 {'Label': 'PSE', 'Count': 15920},
 {'Label': 'NYS', 'Count': 15541},
 {'Label': 'NTV', 'Count': 15090},
 {'Label': 'BZX', 'Count': 14982},
 {'Label': 'BYX', 'Count': 14980},
 {'Label': 'CIN', 'Count': 13961},
 {'Label': 'NYQ', 'Count': 13610},
 {'Label': 'BT1', 'Count': 13244},
 {'Label': 'ARC', 'Count': 12685},
 {'Label': 'NMS', 'Count': 12119},
 {'Label': 'NQT', 'Count': 11239},
 {'Label': 'AOI', 'Count': 10465},
 {'Label': 'NOI', 'Count': 10465},
 {'Label': 'WCB', 'Count': 9915},
 {'Label': 'ADC', 'Count': 9570},
 {'Label': 'DXX', 'Count': 9368},
 {'Label': 'NXB', 'Count': 8939},
 {'Label': 'ASE', 'Count': 8603},
 {'Label': 'BAT', 'Count': 8275},
 {'Label': 'BON', 'Count': 7996},
 {'Label': 'DEA', 'Count': 7487},
 {'Label': 'DEX', 'Count': 7487},
 {'Label': 'BTY', 'Count': 7378},
 {'Label': 'CBF', 'Count': 7084},
 {'Label': 'BEX', 'Count': 6828},
 {'Label': 'NBN', 'Count': 5873},
 {'Label': 'IEX', 'Count': 5586},
 {'Label': 'SCC', 'Count': 5376},
 {'Label': 'ISJ', 'Count': 5357},
 {'Label': 'SCB', 'Count': 5340},
 {'Label': 'MPO', 'Count': 5276},
 {'Label': 'ADS', 'Count': 5266},
 {'Label': 'SCP', 'Count': 5082},
 {'Label': 'SCX', 'Count': 5031}]

#### Segmenting the search
When we started with the above search to retrieve the list of exchange codes within the United States, we discovered that the result set returned the entire universe of instruments.  If our goal is to capture the entire instrument list, we cannot group and bucket the result set as we did above.  The # of hits returned is nearly 5 million so we are forced to go through a tedious process of segmenting the requests.

One way to do this is to choose some kind of indicator that will allow you to group your individual requests to successfully segment the result set.  However, you need to first ask yourself - do I need the entire data universe?  You may only be interested in a specific asset category thus reducing the universe of results significantly.

One possible way to approach this is to first capture the list of asset categories using a navigator on the property: 'RCSAssetCategoryLeaf'.  
For example:

In [12]:
response=search.Definition(
    view = search.Views.EQUITY_QUOTES,
    filter = "RCSExchangeCountryLeaf eq 'United States'",
    top = 0,
    navigators = "RCSAssetCategoryLeaf"
).get_data()
response.data.raw['Navigators']['RCSAssetCategoryLeaf']['Buckets']

[{'Label': 'Equity Cash Option', 'Count': 2054869},
 {'Label': 'Equity Future', 'Count': 1453464},
 {'Label': 'Ordinary Share', 'Count': 502937},
 {'Label': 'Stock Index Future Option', 'Count': 243470},
 {'Label': 'Stock Index Cash Option', 'Count': 145170},
 {'Label': 'Equity Future Spread', 'Count': 129748},
 {'Label': 'Unit', 'Count': 58161},
 {'Label': 'Bond', 'Count': 57594},
 {'Label': 'Stock Index Future', 'Count': 43678},
 {'Label': 'American Depository Receipt', 'Count': 36389},
 {'Label': 'Preferred Share', 'Count': 23876},
 {'Label': 'Company Warrant', 'Count': 13367},
 {'Label': 'Right', 'Count': 12880},
 {'Label': 'Preference Share', 'Count': 12838},
 {'Label': 'Depository Share', 'Count': 9911},
 {'Label': 'Depository Receipt', 'Count': 8163},
 {'Label': 'Equity-Linked Security', 'Count': 8156},
 {'Label': 'Fully Paid Ordinary Share', 'Count': 7530},
 {'Label': 'Index-Linked Security', 'Count': 4436},
 {'Label': 'Membership Interest Security', 'Count': 4075},
 {'Label': 'Convertible Preference Share', 'Count': 3079},
 {'Label': 'Cumulative Preference Share', 'Count': 2192},
 {'Label': 'Currency Cash Option', 'Count': 2021},
 {'Label': 'Global Depository Receipt', 'Count': 1343},
 {'Label': 'Investment Certificate', 'Count': 1138},
 {'Label': 'Equity Market Statistics', 'Count': 1016},
 {'Label': 'Enhanced Trust Preferred Security', 'Count': 941},
 {'Label': 'Thai Non-Voting Depository Receipt', 'Count': 481},
 {'Label': 'Guarantee Certificate', 'Count': 433},
 {'Label': 'Subscription Right', 'Count': 376},
 {'Label': 'Non-Cumulative Preference Share', 'Count': 294},
 {'Label': 'ETF Future', 'Count': 280},
 {'Label': 'Currency Future', 'Count': 239},
 {'Label': 'Stapled Security', 'Count': 233},
 {'Label': 'CHESS Depository Interest', 'Count': 204},
 {'Label': 'Equity Future Option', 'Count': 181},
 {'Label': 'Redeemable Preference Share', 'Count': 128},
 {'Label': 'Spread', 'Count': 110},
 {'Label': 'Future', 'Count': 68},
 {'Label': 'Commodity ETF', 'Count': 61},
 {'Label': 'Equity', 'Count': 54},
 {'Label': 'ETF Option', 'Count': 43},
 {'Label': 'Interest Rate-Linked Security', 'Count': 41},
 {'Label': 'Swedish Depository Receipt', 'Count': 40},
 {'Label': 'Commodity-Linked Security', 'Count': 36},
 {'Label': 'Savings Share', 'Count': 36},
 {'Label': 'Mexican Ordinary Participation Certificate', 'Count': 25},
 {'Label': 'Participation Share', 'Count': 25},
 {'Label': 'Participating Preference Share', 'Count': 23},
 {'Label': 'Redemption Share', 'Count': 22},
 {'Label': 'Dutch Certificate', 'Count': 17},
 {'Label': 'Peruvian Investment Share', 'Count': 17},
 {'Label': 'Deferred Share', 'Count': 16},
 {'Label': 'Open-End Fund', 'Count': 10},
 {'Label': 'Stock Dividend', 'Count': 10},
 {'Label': 'Option', 'Count': 7},
 {'Label': 'Closed-End Fund', 'Count': 6},
 {'Label': 'Brazilian Depository Receipt', 'Count': 5},
 {'Label': 'Brazilian Unit', 'Count': 5},
 {'Label': 'Commodity Indicator / Statistic', 'Count': 4},
 {'Label': 'Ordinary Subscription Receipt', 'Count': 4},
 {'Label': 'Philippine Depository Receipt', 'Count': 4},
 {'Label': 'European Depository Receipt', 'Count': 3},
 {'Label': 'Genussschein', 'Count': 3},
 {'Label': 'Partly Paid Ordinary Share', 'Count': 3},
 {'Label': 'Traditional Warrant', 'Count': 3},
 {'Label': 'Commodity Fundamentals', 'Count': 2},
 {'Label': 'Paid Subscription Share', 'Count': 2},
 {'Label': 'Subscription Option', 'Count': 2},
 {'Label': 'Bond Future Spread', 'Count': 1},
 {'Label': 'Currency Future Option', 'Count': 1},
 {'Label': 'Income Deposit Security', 'Count': 1},
 {'Label': 'Nil Paid Ordinary Share', 'Count': 1},
 {'Label': 'Option Right', 'Count': 1},
 {'Label': 'Tracker Certificate', 'Count': 1}]

The result of this will not only provide the complete list of categories for you to potentially select the desired ones, but for each, you can see the number of results.  This will further allow you to tune your requests based on these totals.

However, the above summary shows many categories that easily exceed the limits of the server.  If you need to further segment, you can possibly use the ***market cap*** to <i>bucket</i> the asset categories, which allows you to pull down each segment.

For example, let's choose an asset category where we can get a breakdown of the market cap:

In [18]:
# The following navigator will prepare the buckets of evenly distributed market cap ranges such that they fulfill 
# the limit requirements.  Below, I chose 14 as this will produce reasonable buckets we can work with.
#
# Note: The value of 14 was random.  I specifically chose this value such that the 'Count' value was within the 10,000 hit limit.
response=search.Definition(
    view = search.Views.EQUITY_QUOTES,
    filter = "RCSExchangeCountryLeaf eq 'United States' and RCSAssetCategoryLeaf xeq 'Ordinary Share'",
    top = 0,
    navigators = "MktCapTotal(type:range, buckets:14)"
).get_data()
response.data.raw["Navigators"]["MktCapTotal"]["Buckets"]

[{'Label': 'Below 1579762.68',
  'Filter': 'MktCapTotal lt 1579762.68',
  'Count': 9665},
 {'Label': 'Between 1579762.68 And 8111989.65',
  'Filter': '(MktCapTotal ge 1579762.68 and MktCapTotal lt 8111989.65)',
  'Count': 9656},
 {'Label': 'Between 8111989.65 And 23494415',
  'Filter': '(MktCapTotal ge 8111989.65 and MktCapTotal lt 23494415)',
  'Count': 9636},
 {'Label': 'Between 23494415 And 56063497.79',
  'Filter': '(MktCapTotal ge 23494415 and MktCapTotal lt 56063497.79)',
  'Count': 9662},
 {'Label': 'Between 56063497.79 And 111984173.76',
  'Filter': '(MktCapTotal ge 56063497.79 and MktCapTotal lt 111984173.76)',
  'Count': 9675},
 {'Label': 'Between 111984173.76 And 212814362.36',
  'Filter': '(MktCapTotal ge 111984173.76 and MktCapTotal lt 212814362.36)',
  'Count': 9643},
 {'Label': 'Between 212814362.36 And 348504871.21',
  'Filter': '(MktCapTotal ge 212814362.36 and MktCapTotal lt 348504871.21)',
  'Count': 9666},
 {'Label': 'Between 348504871.21 And 586152153.94',
  'Filter': '(MktCapTotal ge 348504871.21 and MktCapTotal lt 586152153.94)',
  'Count': 9639},
 {'Label': 'Between 586152153.94 And 1029991219.66',
  'Filter': '(MktCapTotal ge 586152153.94 and MktCapTotal lt 1029991219.66)',
  'Count': 9646},
 {'Label': 'Between 1029991219.66 And 1784074543.6',
  'Filter': '(MktCapTotal ge 1029991219.66 and MktCapTotal lt 1784074543.6)',
  'Count': 9648},
 {'Label': 'Between 1784074543.6 And 3226143300.18',
  'Filter': '(MktCapTotal ge 1784074543.6 and MktCapTotal lt 3226143300.18)',
  'Count': 9679},
 {'Label': 'Between 3226143300.18 And 5992611317.7',
  'Filter': '(MktCapTotal ge 3226143300.18 and MktCapTotal lt 5992611317.7)',
  'Count': 9628},
 {'Label': 'Between 5992611317.7 And 15412510470.57',
  'Filter': '(MktCapTotal ge 5992611317.7 and MktCapTotal lt 15412510470.57)',
  'Count': 9644},
 {'Label': 'Above 15412510470.57',
  'Filter': 'MktCapTotal ge 15412510470.57',
  'Count': 9667}]

The first thing to note is that the 'Count' values for each bucket are within the valid limit of the server.  Based on this output, we can use the convenient Filter expressions provided to drive our segmented search requests.

For demonstration purposes, I will select one to retrieve the list of RICs for the specific asset category with the specified market cap range.

In [20]:
# Define our filter
range1 = response.data.raw["Navigators"]["MktCapTotal"]["Buckets"][1]["Filter"]
filter = f"RCSExchangeCountryLeaf eq 'United States' and RCSAssetCategoryLeaf xeq 'Ordinary Share' and {range1}"
filter

"RCSExchangeCountryLeaf eq 'United States' and RCSAssetCategoryLeaf xeq 'Ordinary Share' and (MktCapTotal ge 1579762.68 and MktCapTotal lt 8111989.65)"

In [22]:
# Request to retrieve the first buckek using the above filter expression I created.
response = search.Definition(
    view = search.Views.EQUITY_QUOTES,
    filter = filter,
    top = 10000
).get_data()
f'Request resulted in a segement of {response.total} documents.'

'Request resulted in a segement of 9656 documents.'

Based on the buckets I defined, I can now safely use a filter to pull out a segment of instruments.  Despite using a combination of navigators and filters to conveniently define how to break up the segments to avoid these limits, the work to do so is still relatively complicated.

While it may be possible to pull out excessive amounts of data, you should ask yourself if you need to do this.  In most cases, you may be able to reduce the result set when you set up your search instead of pulling in everything then massage the results once you have them in hand.  Search was designed specifically to allow users to filter out unwanted content prior to returning the results.  If you think this way through your searching patterns, you will undoubtedly avoid situations where you need to create complicated algorithms to unnecessarily pull excessive amounts of data. Whether narrowing the request based on interested categories, or data for a specific region, you will find that you can significantly simplify your logic and avoid issues with limits.

In [23]:
ld.close_session()