## Filter
One of the most powerful parameters when defining a search is the ability to filter the results.  While a Query is more of an unstructured approach to search for text within documents, a Filter provides a well-defined structured approach when we know which properties we want to restrict our matching documents.

The following examples will be using some of the popular properties as outlined within the "Properties & Metadata" notebook.  In addition, the selection of these properties was determined based on the discovery techniques used such as metadata and debugging.

In [1]:
import lseg.data as ld
from lseg.data.content import search
import pandas as pd
import datetime as dt
import dateutil.relativedelta

# Default session - desktop
ld.open_session()

In [2]:
pd.set_option('display.max_colwidth', 140)
ld.__version__

'2.1.1'

#### Example - Query vs Filter
As you become more familiar with Search, you will realize there are a number of different paths you can take to arrive at the same destination.

In [5]:
# Retrieve the document(s) for a specific ISIN using a Query.
ld.discovery.search(
    view = search.Views.INSTRUMENTS,
    query = 'US046353AQ14',
    select = 'DocumentTitle, IssuerEquityPrimaryRIC, ISIN, CUSIP, SEDOL, PermID'
)

,DocumentTitle,IssuerEquityPrimaryRIC,ISIN,CUSIP,SEDOL,PermID
0,"AstraZeneca PLC, Plain Vanilla Fixed Coupon Bond, TRACE Eligible AZN 2.375 12-Jun-2022",AZN.L,US046353AQ14,046353AQ1,BF4SNM7,46645702869

In [6]:
# Retrieve the document(s) for the same ISIN using a Filter
ld.discovery.search(
    view = search.Views.INSTRUMENTS,
    filter = "ISIN eq 'US046353AQ14'",
    select = 'DocumentTitle, IssuerEquityPrimaryRIC, ISIN, CUSIP, SEDOL, PermID'
)

,DocumentTitle,IssuerEquityPrimaryRIC,ISIN,CUSIP,SEDOL,PermID
0,"AstraZeneca PLC, Plain Vanilla Fixed Coupon Bond, TRACE Eligible AZN 2.375 12-Jun-2022",AZN.L,US046353AQ14,046353AQ1,BF4SNM7,46645702869

In [7]:
# If you are provided a code but are not sure if the code is an ISIN, SEDOL, CUSIP etc, 
# try using the 'CodeResolutionBase' property.
ld.discovery.search(
    view = search.Views.INSTRUMENTS,
    filter = "CodeResolutionBase eq '046353AQ1'",   # I'm using the CUSIP for the same instrument
    select = 'DocumentTitle, IssuerEquityPrimaryRIC, ISIN, CUSIP, SEDOL, PermID'
)

,DocumentTitle,IssuerEquityPrimaryRIC,ISIN,CUSIP,SEDOL,PermID
0,"AstraZeneca PLC, Plain Vanilla Fixed Coupon Bond, TRACE Eligible AZN 2.375 12-Jun-2022",AZN.L,US046353AQ14,046353AQ1,BF4SNM7,46645702869

#### Example - Apple Equities

In [8]:
# Within the view (EquityQuotes), select all documents where the term 'AAPL' is within the ticker symbol.  For each, 
# ensure the type of asset is an 'equity' and that each asset is in an active state.  I chose to filter out the 
# AssetState of 'DC' (De-activated) as my criteria. By default, the top 10 results are presented.
#
# Note: An alternative to "AssetType eq 'equity'" could be to used: "RCSAssetCategoryLeaf eq 'Ordinary Share'"
ld.discovery.search(
    view = search.Views.EQUITY_QUOTES,
    filter = "AssetType eq 'equity' and AssetState ne 'DC' and TickerSymbol eq 'AAPL'",
    select = "RIC, CompositeDescriptiveName, ExchangeCode, ExchangeName, AssetType"
)

,RIC,CompositeDescriptiveName,ExchangeCode,ExchangeName,AssetType
0,AAPL.O,Apple Ord Shs APPLE ORD,NSQ,NASDAQ Global Select Consolidated,[EQUITY]
1,AAPL.TO,APPLE CAD HEDGED CDR Apple CAD Hedged CDR AIRBNB,TOR,The Toronto Stock Exchange,[EQUITY]
2,AAPL.OQ,Apple Ord Shs APPLE ORD,NSM,NASDAQ Stock Exchange Global Select Market,[EQUITY]
3,AAPL.Z,Apple Ord Shs APPLE ORD APPLE INC,GCZ,Cboe BZX Exchange - Nasdaq Global Select Market,[EQUITY]
4,AAPL.DG,Apple Ord Shs APPLE ORD,GCD,Cboe EDGX Exchange - Nasdaq Global Select Market,[EQUITY]
5,AAPL.B,Apple Ord Shs APPLE ORD,GSB,Boston SE when trading NASDAQ Global Select Market,[EQUITY]
6,AAPL.CCP,APPLE CAD HEDGED CDR Apple CAD Hedged CDR,CAQ,Canadian Composite Quote/Trade,[EQUITY]
7,AAPL.GO,APPLE CAD HEDGED CDR Apple CAD Hedged CDR,PTX,Canadian Securities Exchange/PURE - CSE Listed & Other Canadian Listed Securities,[EQUITY]
8,AAPL.DY,Apple Ord Shs APPLE ORD,GDA,Cboe EDGA Exchange - Nasdaq Global Select Market,[EQUITY]
9,AAPL.ZY,Apple Ord Shs APPLE ORD APPLE INC,GCY,Cboe BYX Exchange - Nasdaq Global Select Market,[EQUITY]

#### Example - Vessels
List all Very Large Gas Containers (VLGC) that are in serviced within the last week.

In [ ]:
# Build date range expression for the location of the vessel for the last 7 days
date_7_days_ago = dt.datetime.today() - dateutil.relativedelta.relativedelta(days=7)
date_range = (
    f"LocationTimestamp ge {date_7_days_ago:%Y-%m-%d} and "
    f"LocationTimestamp lt {dt.datetime.today():%Y-%m-%d}"
)

date_range

'LocationTimestamp ge 2026-03-06 and LocationTimestamp lt 2026-03-13'

In [14]:
# Show the location of each vessel and some general details such as location, destination and coordinates.
# If available, show the top 100 hits.
ld.discovery.search(
    view = search.Views.VESSEL_PHYSICAL_ASSETS,
    filter = f"RCSAssetTypeLeaf eq 'VLGC' and VesselStatus eq 'IN SERVICE' and {date_range}",
    select = 'RIC, SynonymSearchAll, DTSource, LocationTimestamp, IMO,Latitude, Longitude, LocationDestination',
    top=100
)

,RIC,SynonymSearchAll,DTSource,LocationTimestamp,IMO,Latitude,Longitude,LocationDestination
0,C}KY7309491970,Indonesian Liquefied Petroleum Gas Very Large Gas Carrier,Gulf of Oman|Arabian Gulf Tanker Zone,2026-03-09T10:58:23.000Z,9350288,25.502001,56.360905,AE FJR [Fujairah]
1,C}KY7309493657,Liquefied Petroleum Gas Very Large Gas Carrier,Gulf of Oman|Arabian Gulf Tanker Zone,2026-03-12T14:53:57.000Z,9370537,25.881039,57.082985,KHORFAKAN [Khor Fakkan]
2,C}KY7309990165,Liquefied Petroleum Gas Very Large Gas Carrier,Gulf of Oman|Arabian Gulf Tanker Zone,2026-03-11T13:58:08.000Z,9923085,25.900963,55.496449,DUBAI ANCHORAGE [Dubai]
3,C}KY7309491971,Liquefied Petroleum Gas Very Large Gas Carrier,Gulf of Oman|Arabian Gulf Tanker Zone,2026-03-12T12:23:55.000Z,9350290,25.385307,55.105247,RASHID DUBAI
4,C}KY7309475170,India Indian Chinese Liquefied Petroleum Gas Very Large Gas Carrier,West Indian Ocean|West Coast India Tanker Zone,2026-03-06T04:02:58.000Z,9134294,9.72323,71.991692,AEKLF OPL [Khor Fakkan]
5,C}KY7309488246,Chinese Liquefied Petroleum Gas Very Large Gas Carrier,South China Sea|Canton Tanker Zone,2026-03-09T22:37:20.000Z,9306548,21.678064,116.909363,"JIAXING,CHINA"
6,C}KY7309482943,Liquefied Petroleum Gas Very Large Gas Carrier,Gulf of Oman|Arabian Gulf Tanker Zone,2026-03-07T03:50:56.000Z,9238284,25.355261,57.032944,AE KHORFFAKAN
7,C}KY7309497589,Liquefied Petroleum Gas Very Large Gas Carrier Indian,Gulf of Oman|Arabian Gulf Tanker Zone,2026-03-12T13:26:33.000Z,9415686,24.483423,52.519932,RUWAIS [Jebel Dhanna/Ruwais]
8,C}KY7309486196,Chinese Liquefied Petroleum Gas Very Large Gas Carrier,South China Sea|Canton Tanker Zone|Taiwan Strait Waypoint,2026-03-12T13:05:53.000Z,9282106,24.235483,118.891701,TO ORDER
9,C}KY7309491637,Liquefied Petroleum Gas Very Large Gas Carrier,Gulf of Oman|Arabian Gulf Tanker Zone,2026-03-10T07:56:24.000Z,9346122,24.712465,53.789494,AEKHL
10,C}KY7309471957,Liquefied Petroleum Gas Very Large Gas Carrier,Gulf of Oman|Arabian Gulf Tanker Zone,2026-03-12T13:08:03.000Z,9088536,25.218782,54.593235,AE SHJ [Mina Khalid (Sharjah)]
11,C}KY7309469310,Liquefied Petroleum Gas Very Large Gas Carrier,Gulf of Oman|Arabian Gulf Tanker Zone,2026-03-12T19:58:42.000Z,9046784,24.939682,54.237305,AEDXB DUBAI DRYDOCK [Dubai]
12,C}KY7309479647,Liquefied Petroleum Gas Very Large Gas Carrier,Gulf of Oman|Arabian Gulf Tanker Zone,2026-03-06T13:32:33.000Z,9193721,25.345118,57.010132,AE KLF

#### Example - Floating Rate Notes
Retrieve all floating rate notes (floating coupon) in the healthcare sector which are issued in Euros.  For each, ensure the coupon rate is great than 2 and our Moody's rating is greater than 'Baa1'.

To determine the rating, we apply the following logic utilizing the RatingsScope property - which is a nested property providing additional details:

- RatingsScope(RatingType eq 'MIS' and CurrentRatingRank lt 10)

The RatingType of 'MIS' refers to the "Moody's Long-term Issuer Rating".
The CurrentRatingRank < 10 instructs search to look for ratings less than 10 ('Baa1').  **Note**: The lower the rank, the better the rating.

In [15]:
ld.discovery.search(
    view = search.Views.GOV_CORP_INSTRUMENTS,
    filter = "CouponRate gt 2 and \
              RatingsScope(RatingType eq 'MIS' and CurrentRatingRank lt 10) and \
              RCSCouponTypeName eq 'Floating Coupon' and \
              IsActive eq true and \
              RCSTRBC2012Name eq 'Healthcare' and \
              RCSCurrencyLeaf xeq 'Euro'",
    select = "CouponCurrency, IssuerName, IssueDate, RIC, CouponRate, ISIN, Ticker, RCSTRBC2012Leaf, MaturityDate, AssetState",   
)

,CouponCurrency,IssuerName,IssueDate,RIC,CouponRate,ISIN,Ticker,RCSTRBC2012Leaf,MaturityDate,AssetState
0,EUR,Sanofi FR,1983-07-01,FR0000140022=,10.0,FR0000140022,SASY,Pharmaceuticals (NEC),NaT,<NA>
1,EUR,Sanofi FR,1987-10-01,FR0000047656=,15.973,FR0000047656,SASY,Pharmaceuticals (NEC),NaT,<NA>
2,EUR,Sanofi FR,2025-03-11,FR001400Y1H8=,2.378,FR001400Y1H8,SASY,Pharmaceuticals (NEC),2027-03-11,AC

#### Example - Outstanding Green Bonds
List the outstanding Green Bonds for Telefonica.

In [16]:
ld.discovery.search(
    view = search.Views.GOV_CORP_INSTRUMENTS,
    filter = "IssuerName eq 'Telefonica' and IsGreenBond eq true",
    select = "IssuerName, DocumentTitle, RIC, CouponRate, ISIN, IssuerTicker, DebtTypeDescription, EOMAmountOutstanding, FaceOutstanding"
)

,IssuerName,DocumentTitle,RIC,CouponRate,ISIN,IssuerTicker,DebtTypeDescription,EOMAmountOutstanding,FaceOutstanding
0,Telefonica Emis,"Telefonica Emisiones SAU, Bond, TEFEMI 4.881",ES326249637=,4.881,XS3262496378,TEFEMI,Junior Subordinated Note,850000000,850000000
1,Telefonica Europ,"Telefonica Europe BV, Bond, TEF 5.752",ES275553557=,5.7522,XS2755535577,TEFBV,Junior Subordinated Note,1100000000,1100000000
2,Telefonica Europ,"Telefonica Europe BV, Bond, TEFBV 2.502",ES210981985=,2.502,XS2109819859,TEFBV,Junior Subordinated Note,500000000,500000000
3,Telefonica Europ,"Telefonica Europe BV, Bond, TEFBV 6.75",ES264660840=,6.75,XS2646608401,TEFBV,Junior Subordinated Note,950000000,950000000
4,Telefonica Emis,"Telefonica Emisiones SAU, Bond, TEFEMI 4.381",ES326249602=,4.381,XS3262496022,TEFEMI,Junior Subordinated Note,900000000,900000000
5,Telefonica Europ,"Telefonica Europe BV, Bond, TEFBV 6.135",ES258238915=,6.135,XS2582389156,TEFBV,Junior Subordinated Note,1000000000,1000000000
6,Telefonica Emis,"Telefonica Emisiones SAU, Plain Vanilla Fixed Coupon Bond, TEFEMI 3.698 24-Jan-2032",ES275331082=,3.698,XS2753310825,TEFEMI,Senior Note,1000000000,1000000000
7,Telefonica Emis,"Telefonica Emisiones SAU, Plain Vanilla Fixed Coupon Bond, TEFEMI 3.707 02-May-2033",ES328500663=,3.707,XS3285006634,TEFEMI,Senior Note,1000000000,1000000000
8,Telefonica Emis,"Telefonica Emisiones SAU, Plain Vanilla Fixed Coupon Bond, TEF 4.183 21-Nov-2033",ES272216231=,4.183,XS2722162315,TEFEMI,Senior Note,850000000,850000000
9,Telefonica Emis,"Telefonica Emisiones SAU, Plain Vanilla Fixed Coupon Bond, TEFEMI 4.055 24-Jan-2036",ES275331139=,4.055,XS2753311393,TEFEMI,Senior Note,750000000,750000000

#### Example - Equity Index listing in the U.S.A

In [17]:
# Based on the Asset Category (Equity Index), list the top 10 indexes within the USA.
ld.discovery.search(
    view = search.Views.INDEX_INSTRUMENTS,
    filter = "RCSIndexCountryGroupLeaf xeq 'United States' and RCSAssetCategoryLeaf xeq 'Equity Index'",
    select = "DocumentTitle, RIC, RCSTRBC2012Leaf"
)

,DocumentTitle,RIC,RCSTRBC2012Leaf
0,"NASDAQ 100 Index, Equity Index",.NDX,UK Investment Trusts
1,"S&P 500 Index - CBOE, Equity Index",.SPX,Securities & Commodity Exchanges
2,"NASDAQ Composite Index, Equity Index",.IXIC,Financial & Commodity Market Operators & Service Providers (NEC)
3,"Dow Jones Industrial Average Index, Equity Index",.DJI,Consumer Publishing (NEC)
4,"FR United States Price Return Index, Equity Index",.TRXFLDUSP,Professional Information Services (NEC)
5,"FR United States Financials Price Return Index, Equity Index",.TRXFLDUSPFIN,Professional Information Services (NEC)
6,"FR United States Technology Price Return Index, Equity Index",.TRXFLDUSPTEC,Professional Information Services (NEC)
7,"FR United States Healthcare Price Return Index, Equity Index",.TRXFLDUSPHLC,Professional Information Services (NEC)
8,"FR United States Consumer Cyclicals Price Return Index, Equity Index",.TRXFLDUSPYCY,Professional Information Services (NEC)
9,"FR United States Industrials Price Return Index, Equity Index",.TRXFLDUSPIND,Professional Information Services (NEC)

#### Example - Search for Brazil global sovereign bonds in USD with a duration greater than 1

In [18]:
ld.discovery.search(
    view=search.Views.FIXED_INCOME_INSTRUMENTS,
    filter = "RCSIssuerCountryLeaf eq 'Brazil' and \
              RCSCurrencyLeaf eq 'US Dollar' and \
              RCSTRBC2012Leaf eq 'Government & Government Finance' and \
              OptionAdjustedDuration gt 1",
    select ="RIC, ISIN, MaturityDate, CouponRate, IndustrySector, FaceOutstandingUSD, OptionAdjustedDuration"
)

,RIC,ISIN,MaturityDate,CouponRate,IndustrySector,FaceOutstandingUSD,OptionAdjustedDuration
0,105756AE0=,US105756AE07,2027-05-15,10.125,SOVERGRN,765023000,1.081709
1,105756BZ2=,US105756BZ27,2028-01-13,4.625,SOVERGRN,3000000000,1.628301
2,105756CA6=,US105756CA66,2029-05-30,4.5,SOVERGRN,2000000000,2.829072
3,BR010862957=,US105756AL40,2030-03-06,12.25,SOVERGRN,237592000,3.28975
4,105756CC2=,US105756CC23,2030-06-12,3.875,SOVERGRN,3500000000,3.814365
5,105756CM0=,US105756CM05,2030-11-06,5.5,SOVERGRN,2250000000,3.994138
6,105756CG3=,US105756CG37,2031-03-18,6.25,SOVERGRN,2000000000,4.166837
7,105756CE8=,US105756CE88,2031-09-12,3.75,SOVERGRN,1500000000,4.865646
8,105756CK4=,US105756CK49,2032-01-22,6.125,SOVERGRN,2000000000,4.854395
9,105756CP3=,US105756CP36,2033-02-04,5.5,SOVERGRN,1500000000,5.562349

In [19]:
# Alternatively, you have the option of trying it this way which will render the same results
# using alternative filter properties, i.e. IssuerCountryName, IndustrySectorDescrioption and Currency
ld.discovery.search(
    view=search.Views.FIXED_INCOME_INSTRUMENTS,
    filter = "IssuerCountryName eq 'Brazil' and \
              OptionAdjustedDuration gt 1 and \
              Currency eq 'USD' and IndustrySectorDescription eq 'Sovereign'",
    select ="RIC, ISIN, MaturityDate, CouponRate,IndustrySector, FaceOutstandingUSD, OptionAdjustedDuration"
)

,RIC,ISIN,MaturityDate,CouponRate,IndustrySector,FaceOutstandingUSD,OptionAdjustedDuration
0,105756AE0=,US105756AE07,2027-05-15,10.125,SOVERGRN,765023000,1.081709
1,105756BZ2=,US105756BZ27,2028-01-13,4.625,SOVERGRN,3000000000,1.628301
2,105756CA6=,US105756CA66,2029-05-30,4.5,SOVERGRN,2000000000,2.829072
3,BR010862957=,US105756AL40,2030-03-06,12.25,SOVERGRN,237592000,3.28975
4,105756CC2=,US105756CC23,2030-06-12,3.875,SOVERGRN,3500000000,3.814365
5,105756CM0=,US105756CM05,2030-11-06,5.5,SOVERGRN,2250000000,3.994138
6,105756CG3=,US105756CG37,2031-03-18,6.25,SOVERGRN,2000000000,4.166837
7,105756CE8=,US105756CE88,2031-09-12,3.75,SOVERGRN,1500000000,4.865646
8,105756CK4=,US105756CK49,2032-01-22,6.125,SOVERGRN,2000000000,4.854395
9,105756CP3=,US105756CP36,2033-02-04,5.5,SOVERGRN,1500000000,5.562349

#### Example - Top executives

In [20]:
# Using the People View, we can utilize the OfficerDirector property, which contains a number of nested or sub-properties 
# that allow me to perform a more fine-grained search against active people that have been assigned a title code of 
# CEO (Chief Executive Officer). The results are listed based on a default rank defined by the search service.
ld.discovery.search(
    view = search.Views.PEOPLE,
    filter = "OfficerDirector(RoleTitleCode eq 'CEO' and RoleStatus eq 'Active')",
    top = 20,
    select = "FullName, PrimaryTitleAsReported, PrimaryOfficerDirector, RIC, OfficerDirectorActiveCompanies, PrimaryOfficerDirectorRIC"
)

,FullName,PrimaryTitleAsReported,PrimaryOfficerDirector,OfficerDirectorActiveCompanies,PrimaryOfficerDirectorRIC
0,Satya Nadella,"Chairman of the Board, Chief Executive Officer",Microsoft Corp,"[Starbucks Corp, Chandler Insurance Company Ltd, Microsoft Pty Ltd, Alpine SG LLC, Microsoft Corp]",MSFT.O
1,John W. Stanton,Independent Director,Microsoft Corp,"[Trilogy Equity Partners LLC, Microsoft Pty Ltd, Russ Pharmaceuticals Inc, Hutchison Asia Telecommunications Ltd, Costco Wholesale Corp,...",MSFT.O
2,Tim D. Cook,"Chief Executive Officer, Director",Apple Inc,"[Apple Inc, Nike Inc]",AAPL.O
3,Andrew R. Jassy,"President, Chief Executive Officer, Director",Amazon.com Inc,"[Coupa Software Inc, Amazon.com Inc]",AMZN.O
4,Sundar Pichai,"Chief Executive Officer, Director",Alphabet Inc,"[Alphabet Inc, Ruba Inc (Fka Kudo Inc)]",GOOGL.O
5,R. Martin Chavez,Director,Alphabet Inc,"[Alphabet Inc, Quorum Software Systems Inc, Kiodex Inc]",GOOGL.O
6,Mark Zuckerberg,"Chairman of the Board, Chief Executive Officer, Founder",Meta Platforms Inc,"[Chan Zuckerberg Initiative, LLC, Meta Platforms Inc]",META.O
7,Drew W. Houston,Independent Director,Meta Platforms Inc,"[Dropbox Inc (Pre-Reincorporation), Meta Platforms Inc]",META.O
8,Warren E. Buffett,"Chairman of the Board, Chief Executive Officer",Berkshire Hathaway Inc,"[Grinnell College, Berkshire Hathaway Inc, Kraft Heinz Intermediate Corporation II, Kraft Heinz Foods Co]",BRKa
9,Yongming Wu,"Chief Executive Officer, Director",Alibaba Group Holding Ltd,[Alibaba Group Holding Ltd],BABA.K
10,Huateng Ma,"Executive Chairman of the Board, Chief Executive Officer",Tencent Holdings Ltd,"[Huarong Tianze Investment Co Ltd, Tencent Holdings Ltd, Tencent Technology Beijing Co Ltd]",0700.HK
11,Ryan McInerney,"Chief Executive Officer, Director",Visa Inc,[Visa Inc],V
12,Joaquin Boix Duato,"Chairman of the Board, Chief Executive Officer",Johnson & Johnson,"[Johnson & Johnson, J & J Services Inc]",JNJ
13,Mary Catherine Beckerle,Independent Director,Johnson & Johnson,"[Johnson & Johnson, Huntsman Cancer Institute, Huntsman Corp]",JNJ
14,Darius E Adamczyk,Independent Director,Johnson & Johnson,"[Johnson & Johnson, Honeywell Deutschland Holding GmbH, Honeywell Turki Arabia Ltd]",JNJ
15,Jamie L. Dimon,"Chairman of the Board, Chief Executive Officer",JPMorgan Chase & Co,"[Travelers Property Casualty Insurance Co, Deccan Hospital Corpn Ltd, Clearing House Payments Company LLC, JP Morgan Partners LLC, JPMor...",JPM
16,Daniel E. Pinto,"President, Chief Operating Officer",JPMorgan Chase & Co,"[Chrysalead, Stanhope Capital LLP, JPMorgan Chase & Co, S4 Capital PLC]",JPM
17,Laurent Freixe,"Chief Executive Officer, Member of the Executive Board",Nestle Ltd,"[Nestle Peru S.a, Nestle Ltd, Nestle Argentina S.a, Nestle Holdings, Inc]",NESN.S
18,Doug McMillon,Director,Walmart Inc,[Walmart Inc],WMT.O
19,John R. Furner,"President, Chief Executive Officer, Director",Walmart Inc,"[Walmart Inc, Wal-mart.com Usa, LLC]",WMT.O

#### Example - Live Options
The following example will specify an underlying instrument (RIC) and pull the list of options that are active, i.e. not expired.

In [21]:
# Define our underlying
underlying = "'AAPL.O'"

# To search for our instrument, I'm utilizing the property: 'UnderlyingQuoteRIC'.  The property does not support an 
# exact match 'xeq', so we must use the partial match 'eq' to find all hits. Depending on the instrument you specify, 
# this may introduce additional hits.  For example, if you are using the underlying 'AAPL.O', search will also find a 
# hit on 'AAPL.OQ', for example. To protect against this, we can utilize a combination of the built-in functions, 
# 'startswith' and 'endwith' to perform our match.
ld.discovery.search(
    view = search.Views.EQUITY_DERIVATIVE_QUOTES,
    filter = "AssetState eq 'AC' and \
              startswith(UnderlyingQuoteRIC, " + underlying + ") and \
              endswith(UnderlyingQuoteRIC," + underlying + ") and \
              RCSAssetClass eq 'OPT' and IsChain eq false and \
              ExpiryDate ge " + dt.datetime.today().strftime('%Y-%m-%d'),
    select = "DocumentTitle, RIC, UnderlyingQuoteRIC, ExpiryDate, CallPutOption, StrikePrice",
    top = 10000
)

,DocumentTitle,RIC,UnderlyingQuoteRIC,ExpiryDate,CallPutOption,StrikePrice
0,"OPRA Apple Equity Option 270 Call Mar 2026 , Equity Cash Option, Call 270 USD 20-Mar-2026, OPRA",AAPLC202627000.U,[AAPL.O],2026-03-20,Call,270.0
1,"OPRA Apple Equity Option 275 Call Mar 2026 , Equity Cash Option, Call 275 USD 20-Mar-2026, OPRA",AAPLC202627500.U,[AAPL.O],2026-03-20,Call,275.0
2,"OPRA Apple Equity Option 270 Put Mar 2026 , Equity Cash Option, Put 270 USD 13-Mar-2026, OPRA",AAPLO132627000.U,[AAPL.O],2026-03-13,Put,270.0
3,"OPRA Apple Equity Option 270 Call Mar 2026 , Equity Cash Option, Call 270 USD 13-Mar-2026, OPRA",AAPLC132627000.U,[AAPL.O],2026-03-13,Call,270.0
4,"OPRA Apple Equity Option 265 Put Mar 2026 , Equity Cash Option, Put 265 USD 13-Mar-2026, OPRA",AAPLO132626500.U,[AAPL.O],2026-03-13,Put,265.0
...,...,...,...,...,...,...
3758,"AAPLz0eVkX, Equity Cash Option, 0 USD 18-Dec-2026, Chicago Board Options Exchange",AAPL-z0eVkX.FO,[AAPL.O],2026-12-18,<NA>,0.0
3759,"AAPLz0ells, Equity Cash Option, 0 USD 17-Apr-2026, Chicago Board Options Exchange",AAPL-z0ells.FO,[AAPL.O],2026-04-17,<NA>,0.0
3760,"CBOE Apple PM Settled European Flex Equity option 220 Call Apr 2026 , Equity Cash Option, Call 220 USD 17-Apr-2026, Chicago Board Option...",2AAPLD1726D00220000.FO,[AAPL.O],2026-04-17,Call,220.0
3761,"AAPLz0ef4E, Equity Cash Option, 0 USD 18-Jun-2026, Chicago Board Options Exchange",AAPL-z0ef4E.FO,[AAPL.O],2026-06-18,<NA>,0.0
3762,"CBOE Apple PM Settled European Flex Equity option 270 Call May 2026 , Equity Cash Option, Call 270 USD 15-May-2026, Chicago Board Option...",2AAPLE1526D00270000.FO,[AAPL.O],2026-05-15,Call,270.0

In [22]:
ld.close_session()